export default [
  {
    url: 'https://api.github.com/repos/iptv-org/epg/issues/2547',
    repository_url: 'https://api.github.com/repos/iptv-org/epg',
    labels_url: 'https://api.github.com/repos/iptv-org/epg/issues/2547/labels{/name}',
    comments_url: 'https://api.github.com/repos/iptv-org/epg/issues/2547/comments',
    events_url: 'https://api.github.com/repos/iptv-org/epg/issues/2547/events',
    html_url: 'https://github.com/iptv-org/epg/issues/2547',
    id: 2760418979,
    node_id: 'I_kwDOFLVvtM6kiKaj',
    number: 2547,
    title: 'digiturk.com.tr',
    user: {
      login: 'freearhey',
      id: 7253922,
      node_id: 'MDQ6VXNlcjcyNTM5MjI=',
      avatar_url: 'https://avatars.githubusercontent.com/u/7253922?v=4',
      gravatar_id: '',
      url: 'https://api.github.com/users/freearhey',
      html_url: 'https://github.com/freearhey',
      followers_url: 'https://api.github.com/users/freearhey/followers',
      following_url: 'https://api.github.com/users/freearhey/following{/other_user}',
      gists_url: 'https://api.github.com/users/freearhey/gists{/gist_id}',
      starred_url: 'https://api.github.com/users/freearhey/starred{/owner}{/repo}',
      subscriptions_url: 'https://api.github.com/users/freearhey/subscriptions',
      organizations_url: 'https://api.github.com/users/freearhey/orgs',
      repos_url: 'https://api.github.com/users/freearhey/repos',
      events_url: 'https://api.github.com/users/freearhey/events{/privacy}',
      received_events_url: 'https://api.github.com/users/freearhey/received_events',
      type: 'User',
      user_view_type: 'public',
      site_admin: false
    },
    labels: [
      {
        id: 4542348869,
        node_id: 'LA_kwDOFLVvtM8AAAABDr6-RQ',
        url: 'https://api.github.com/repos/iptv-org/epg/labels/broken%20guide',
        name: 'broken guide',
        color: 'eaeaea',
        default: false,
        description: "There's a problem with the guide"
      },
      {
        id: 7932710795,
        node_id: 'LA_kwDOFLVvtM8AAAAB2NOPiw',
        url: 'https://api.github.com/repos/iptv-org/epg/labels/status:down',
        name: 'status:down',
        color: 'df3a4a',
        default: false,
        description: "The guide doesn't work"
      }
    ],
    state: 'open',
    locked: false,
    assignee: null,
    assignees: [],
    milestone: null,
    comments: 1,
    created_at: '2024-12-27T05:33:47Z',
    updated_at: '2024-12-28T20:37:53Z',
    closed_at: null,
    author_association: 'COLLABORATOR',
    active_lock_reason: null,
    body: '### Site\n\ndigiturk.com.tr\n\n### Description\n\n```sh\r\nnpm run grab --- --site=digiturk.com.tr\r\n\r\n> grab\r\n> npx tsx scripts/commands/epg/grab.ts --site=digiturk.com.tr\r\n\r\nstarting...\r\nconfig:\r\n  output: guide.xml\r\n  maxConnections: 1\r\n  gzip: false\r\n  site: digiturk.com.tr\r\nloading channels...\r\n  found 139 channel(s)\r\nrun #1:\r\n  [1/278] digiturk.com.tr (en) - AlJazeeraEnglish.qa - Dec 27, 2024 (0 programs)\r\n    ERR: Request failed with status code 404\r\n  [2/278] digiturk.com.tr (en) - AlJazeeraEnglish.qa - Dec 28, 2024 (0 programs)\r\n    ERR: Request failed with status code 404\r\n  [3/278] digiturk.com.tr (tr) - Yaban.tr - Dec 28, 2024 (0 programs)\r\n    ERR: Request failed with status code 404\r\n```',
    closed_by: null,
    reactions: {
      url: 'https://api.github.com/repos/iptv-org/epg/issues/2547/reactions',
      total_count: 1,
      '+1': 1,
      '-1': 0,
      laugh: 0,
      hooray: 0,
      confused: 0,
      heart: 0,
      rocket: 0,
      eyes: 0
    },
    timeline_url: 'https://api.github.com/repos/iptv-org/epg/issues/2547/timeline',
    performed_via_github_app: null,
    state_reason: null
  },
  {
    url: 'https://api.github.com/repos/iptv-org/epg/issues/2542',
    repository_url: 'https://api.github.com/repos/iptv-org/epg',
    labels_url: 'https://api.github.com/repos/iptv-org/epg/issues/2542/labels{/name}',
    comments_url: 'https://api.github.com/repos/iptv-org/epg/issues/2542/comments',
    events_url: 'https://api.github.com/repos/iptv-org/epg/issues/2542/events',
    html_url: 'https://github.com/iptv-org/epg/issues/2542',
    id: 2759639980,
    node_id: 'I_kwDOFLVvtM6kfMOs',
    number: 2542,
    title: 'tvguide.com not working',
    user: {
      login: 'SiWafer',
      id: 10903014,
      node_id: 'MDQ6VXNlcjEwOTAzMDE0',
      avatar_url: 'https://avatars.githubusercontent.com/u/10903014?v=4',
      gravatar_id: '',
      url: 'https://api.github.com/users/SiWafer',
      html_url: 'https://github.com/SiWafer',
      followers_url: 'https://api.github.com/users/SiWafer/followers',
      following_url: 'https://api.github.com/users/SiWafer/following{/other_user}',
      gists_url: 'https://api.github.com/users/SiWafer/gists{/gist_id}',
      starred_url: 'https://api.github.com/users/SiWafer/starred{/owner}{/repo}',
      subscriptions_url: 'https://api.github.com/users/SiWafer/subscriptions',
      organizations_url: 'https://api.github.com/users/SiWafer/orgs',
      repos_url: 'https://api.github.com/users/SiWafer/repos',
      events_url: 'https://api.github.com/users/SiWafer/events{/privacy}',
      received_events_url: 'https://api.github.com/users/SiWafer/received_events',
      type: 'User',
      user_view_type: 'public',
      site_admin: false
    },
    labels: [
      {
        id: 4542348869,
        node_id: 'LA_kwDOFLVvtM8AAAABDr6-RQ',
        url: 'https://api.github.com/repos/iptv-org/epg/labels/broken%20guide',
        name: 'broken guide',
        color: 'eaeaea',
        default: false,
        description: "There's a problem with the guide"
      },
      {
        id: 7932710795,
        node_id: 'LA_kwDOFLVvtM8AAAAB2NOPiw',
        url: 'https://api.github.com/repos/iptv-org/epg/labels/status:down',
        name: 'status:down',
        color: 'df3a4a',
        default: false,
        description: "The guide doesn't work"
      }
    ],
    state: 'open',
    locked: false,
    assignee: null,
    assignees: [],
    milestone: null,
    comments: 0,
    created_at: '2024-12-26T11:11:24Z',
    updated_at: '2024-12-27T05:28:55Z',
    closed_at: null,
    author_association: 'NONE',
    active_lock_reason: null,
    body: '### Site\n\ntvguide.com\n\n### Description\n\n```\r\nepg@rpi:~/epg$ npm run grab --- --site=tvguide.com\r\n\r\n> grab\r\n> npx tsx scripts/commands/epg/grab.ts --site=tvguide.com\r\n\r\nstarting...\r\nconfig:\r\n  output: guide.xml\r\n  maxConnections: 1\r\n  gzip: false\r\n  site: tvguide.com\r\nloading channels...\r\n  found 39 channel(s)\r\nrun #1:\r\n  [1/78] tvguide.com (en) - AEEast.us - Dec 26, 2024 (0 programs)\r\n    ERR: Request failed with status code 403\r\n  [2/78] tvguide.com (en) - AEEast.us - Dec 27, 2024 (0 programs)\r\n    ERR: Request failed with status code 403\r\n  [3/78] tvguide.com (en) - AMCEast.us - Dec 27, 2024 (0 programs)\r\n    ERR: Request failed with status code 403\r\n  [4/78] tvguide.com (en) - AMCEast.us - Dec 26, 2024 (0 programs)\r\n    ERR: Request failed with status code 403\r\n  [5/78] tvguide.com (en) - BravoEast.us - Dec 27, 2024 (0 programs)\r\n    ERR: Request failed with status code 403\r\n  [6/78] tvguide.com (en) - BravoEast.us - Dec 26, 2024 (0 programs)\r\n    ERR: Request failed with status code 403\r\n  [7/78] tvguide.com (en) - BBCAmericaEast.us - Dec 27, 2024 (0 programs)\r\n    ERR: Request failed with status code 403\r\n  [8/78] tvguide.com (en) - CNBC.us - Dec 27, 2024 (0 programs)\r\n    ERR: Request failed with status code 403\r\n  [9/78] tvguide.com (en) - CNBC.us - Dec 26, 2024 (0 programs)\r\n...\r\n...\r\n...\r\n```',
    closed_by: null,
    reactions: {
      url: 'https://api.github.com/repos/iptv-org/epg/issues/2542/reactions',
      total_count: 0,
      '+1': 0,
      '-1': 0,
      laugh: 0,
      hooray: 0,
      confused: 0,
      heart: 0,
      rocket: 0,
      eyes: 0
    },
    timeline_url: 'https://api.github.com/repos/iptv-org/epg/issues/2542/timeline',
    performed_via_github_app: null,
    state_reason: null
  },
  {
    url: 'https://api.github.com/repos/iptv-org/epg/issues/2541',
    repository_url: 'https://api.github.com/repos/iptv-org/epg',
    labels_url: 'https://api.github.com/repos/iptv-org/epg/issues/2541/labels{/name}',
    comments_url: 'https://api.github.com/repos/iptv-org/epg/issues/2541/comments',
    events_url: 'https://api.github.com/repos/iptv-org/epg/issues/2541/events',
    html_url: 'https://github.com/iptv-org/epg/issues/2541',
    id: 2758749907,
    node_id: 'I_kwDOFLVvtM6kby7T',
    number: 2541,
    title: 'elcinema.com grab error 403',
    user: {
      login: 'xercessss',
      id: 189765257,
      node_id: 'U_kgDOC0-WiQ',
      avatar_url: 'https://avatars.githubusercontent.com/u/189765257?v=4',
      gravatar_id: '',
      url: 'https://api.github.com/users/xercessss',
      html_url: 'https://github.com/xercessss',
      followers_url: 'https://api.github.com/users/xercessss/followers',
      following_url: 'https://api.github.com/users/xercessss/following{/other_user}',
      gists_url: 'https://api.github.com/users/xercessss/gists{/gist_id}',
      starred_url: 'https://api.github.com/users/xercessss/starred{/owner}{/repo}',
      subscriptions_url: 'https://api.github.com/users/xercessss/subscriptions',
      organizations_url: 'https://api.github.com/users/xercessss/orgs',
      repos_url: 'https://api.github.com/users/xercessss/repos',
      events_url: 'https://api.github.com/users/xercessss/events{/privacy}',
      received_events_url: 'https://api.github.com/users/xercessss/received_events',
      type: 'User',
      user_view_type: 'public',
      site_admin: false
    },
    labels: [
      {
        id: 4542348869,
        node_id: 'LA_kwDOFLVvtM8AAAABDr6-RQ',
        url: 'https://api.github.com/repos/iptv-org/epg/labels/broken%20guide',
        name: 'broken guide',
        color: 'eaeaea',
        default: false,
        description: "There's a problem with the guide"
      },
      {
        id: 7932710795,
        node_id: 'LA_kwDOFLVvtM8AAAAB2NOPiw',
        url: 'https://api.github.com/repos/iptv-org/epg/labels/status:down',
        name: 'status:down',
        color: 'df3a4a',
        default: false,
        description: "The guide doesn't work"
      }
    ],
    state: 'open',
    locked: false,
    assignee: null,
    assignees: [],
    milestone: null,
    comments: 0,
    created_at: '2024-12-25T11:34:16Z',
    updated_at: '2024-12-27T05:28:07Z',
    closed_at: null,
    author_association: 'NONE',
    active_lock_reason: null,
    body: '### Site\n\nelcinema.com\n\n### Description\n\ngrabbing elcinema.com epg return error 403 for both ar and en language:\r\nERR: Request failed with status code 403\r\n',
    closed_by: null,
    reactions: {
      url: 'https://api.github.com/repos/iptv-org/epg/issues/2541/reactions',
      total_count: 0,
      '+1': 0,
      '-1': 0,
      laugh: 0,
      hooray: 0,
      confused: 0,
      heart: 0,
      rocket: 0,
      eyes: 0
    },
    timeline_url: 'https://api.github.com/repos/iptv-org/epg/issues/2541/timeline',
    performed_via_github_app: null,
    state_reason: null
  },
  {
    url: 'https://api.github.com/repos/iptv-org/epg/issues/2509',
    repository_url: 'https://api.github.com/repos/iptv-org/epg',
    labels_url: 'https://api.github.com/repos/iptv-org/epg/issues/2509/labels{/name}',
    comments_url: 'https://api.github.com/repos/iptv-org/epg/issues/2509/comments',
    events_url: 'https://api.github.com/repos/iptv-org/epg/issues/2509/events',
    html_url: 'https://github.com/iptv-org/epg/issues/2509',
    id: 2740938968,
    node_id: 'I_kwDOFLVvtM6jX2jY',
    number: 2509,
    title: 'ssl problem maxtv.hrvatskitelekom.hr',
    user: {
      login: 'uploadkom',
      id: 130712472,
      node_id: 'U_kgDOB8qDmA',
      avatar_url: 'https://avatars.githubusercontent.com/u/130712472?v=4',
      gravatar_id: '',
      url: 'https://api.github.com/users/uploadkom',
      html_url: 'https://github.com/uploadkom',
      followers_url: 'https://api.github.com/users/uploadkom/followers',
      following_url: 'https://api.github.com/users/uploadkom/following{/other_user}',
      gists_url: 'https://api.github.com/users/uploadkom/gists{/gist_id}',
      starred_url: 'https://api.github.com/users/uploadkom/starred{/owner}{/repo}',
      subscriptions_url: 'https://api.github.com/users/uploadkom/subscriptions',
      organizations_url: 'https://api.github.com/users/uploadkom/orgs',
      repos_url: 'https://api.github.com/users/uploadkom/repos',
      events_url: 'https://api.github.com/users/uploadkom/events{/privacy}',
      received_events_url: 'https://api.github.com/users/uploadkom/received_events',
      type: 'User',
      user_view_type: 'public',
      site_admin: false
    },
    labels: [
      {
        id: 4542348869,
        node_id: 'LA_kwDOFLVvtM8AAAABDr6-RQ',
        url: 'https://api.github.com/repos/iptv-org/epg/labels/broken%20guide',
        name: 'broken guide',
        color: 'eaeaea',
        default: false,
        description: "There's a problem with the guide"
      },
      {
        id: 7932710795,
        node_id: 'LA_kwDOFLVvtM8AAAAB2NOPiw',
        url: 'https://api.github.com/repos/iptv-org/epg/labels/status:down',
        name: 'status:down',
        color: 'df3a4a',
        default: false,
        description: "The guide doesn't work"
      }
    ],
    state: 'open',
    locked: false,
    assignee: null,
    assignees: [],
    milestone: null,
    comments: 3,
    created_at: '2024-12-15T22:21:22Z',
    updated_at: '2024-12-27T05:26:26Z',
    closed_at: null,
    author_association: 'NONE',
    active_lock_reason: null,
    body: '### Site\n\nmaxtv.hrvatskitelekom.hr\n\n### Description\n\nssl problem',
    closed_by: null,
    reactions: {
      url: 'https://api.github.com/repos/iptv-org/epg/issues/2509/reactions',
      total_count: 0,
      '+1': 0,
      '-1': 0,
      laugh: 0,
      hooray: 0,
      confused: 0,
      heart: 0,
      rocket: 0,
      eyes: 0
    },
    timeline_url: 'https://api.github.com/repos/iptv-org/epg/issues/2509/timeline',
    performed_via_github_app: null,
    state_reason: null
  },
  {
    url: 'https://api.github.com/repos/iptv-org/epg/issues/2498',
    repository_url: 'https://api.github.com/repos/iptv-org/epg',
    labels_url: 'https://api.github.com/repos/iptv-org/epg/issues/2498/labels{/name}',
    comments_url: 'https://api.github.com/repos/iptv-org/epg/issues/2498/comments',
    events_url: 'https://api.github.com/repos/iptv-org/epg/issues/2498/events',
    html_url: 'https://github.com/iptv-org/epg/issues/2498',
    id: 2728188494,
    node_id: 'I_kwDOFLVvtM6inNpO',
    number: 2498,
    title: 'movistarplus.es',
    user: {
      login: 'freearhey',
      id: 7253922,
      node_id: 'MDQ6VXNlcjcyNTM5MjI=',
      avatar_url: 'https://avatars.githubusercontent.com/u/7253922?v=4',
      gravatar_id: '',
      url: 'https://api.github.com/users/freearhey',
      html_url: 'https://github.com/freearhey',
      followers_url: 'https://api.github.com/users/freearhey/followers',
      following_url: 'https://api.github.com/users/freearhey/following{/other_user}',
      gists_url: 'https://api.github.com/users/freearhey/gists{/gist_id}',
      starred_url: 'https://api.github.com/users/freearhey/starred{/owner}{/repo}',
      subscriptions_url: 'https://api.github.com/users/freearhey/subscriptions',
      organizations_url: 'https://api.github.com/users/freearhey/orgs',
      repos_url: 'https://api.github.com/users/freearhey/repos',
      events_url: 'https://api.github.com/users/freearhey/events{/privacy}',
      received_events_url: 'https://api.github.com/users/freearhey/received_events',
      type: 'User',
      user_view_type: 'public',
      site_admin: false
    },
    labels: [
      {
        id: 4542348869,
        node_id: 'LA_kwDOFLVvtM8AAAABDr6-RQ',
        url: 'https://api.github.com/repos/iptv-org/epg/labels/broken%20guide',
        name: 'broken guide',
        color: 'eaeaea',
        default: false,
        description: "There's a problem with the guide"
      },
      {
        id: 7932710795,
        node_id: 'LA_kwDOFLVvtM8AAAAB2NOPiw',
        url: 'https://api.github.com/repos/iptv-org/epg/labels/status:down',
        name: 'status:down',
        color: 'df3a4a',
        default: false,
        description: "The guide doesn't work"
      }
    ],
    state: 'open',
    locked: false,
    assignee: null,
    assignees: [],
    milestone: null,
    comments: 0,
    created_at: '2024-12-09T20:26:07Z',
    updated_at: '2024-12-27T05:23:48Z',
    closed_at: null,
    author_association: 'COLLABORATOR',
    active_lock_reason: null,
    body: '### Site\n\nmovistarplus.es\n\n### Description\n\n```sh\r\nnpm run grab -- --site=movistarplus.es\r\n\r\n> grab\r\n> npx tsx scripts/commands/epg/grab.ts --site=movistarplus.es\r\n\r\n(node:22362) ExperimentalWarning: `--experimental-loader` may be removed in the future; instead use `register()`:\r\n--import \'data:text/javascript,import { register } from "node:module"; import { pathToFileURL } from "node:url"; register("file%3A///Users/Arhey/Code/iptv-org/epg/node_modules/tsx/dist/loader.mjs", pathToFileURL("./"));\'\r\n(Use `node --trace-warnings ...` to show where the warning was created)\r\n(node:22362) UnsupportedWarning: `globalPreload` has been removed; use `initialize` instead.\r\n(Use `node --trace-warnings ...` to show where the warning was created)\r\nstarting...\r\nconfig:\r\n  output: guide.xml\r\n  maxConnections: 1\r\n  gzip: false\r\n  site: movistarplus.es\r\nloading channels...\r\n(node:22362) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.\r\n  found 186 channel(s)\r\nrun #1:\r\n  [1/372] movistarplus.es (es) - ANTV - Dec 9, 2024 (0 programs)\r\n    ERR: Request failed with status code 404\r\n  [2/372] movistarplus.es (es) - ANTV - Dec 10, 2024 (0 programs)\r\n    ERR: Request failed with status code 404\r\n  [3/372] movistarplus.es (es) - ARAGTV - Dec 10, 2024 (0 programs)\r\n    ERR: Request failed with status code 404\r\n  [4/372] movistarplus.es (es) - CANSUR - Dec 10, 2024 (0 programs)\r\n    ERR: Request failed with status code 404\r\n  [5/372] movistarplus.es (es) - DAZNL2 - Dec 10, 2024 (0 programs)\r\n    ERR: Request failed with status code 404\r\n  [6/372] movistarplus.es (es) - MLIGS - Dec 10, 2024 (0 programs)\r\n    ERR: Request failed with status code 404\r\n  [7/372] movistarplus.es (es) - AMC.es - Dec 10, 2024 (0 programs)\r\n    ERR: Request failed with status code 404\r\n  [8/372] movistarplus.es (es) - ComediaporMovistarPlusPlus.es - Dec 10, 2024 (0 programs)\r\n    ERR: Request failed with status code 404\r\n  [9/372] movistarplus.es (es) - LasEstrellasEuropa.mx - Dec 10, 2024 (0 programs)\r\n    ERR: Request failed with status code 404\r\n  [10/372] movistarplus.es (es) - LasEstrellasEuropa.mx - Dec 9, 2024 (0 programs)\r\n    ERR: Request failed with status code 404\r\n  [11/372] movistarplus.es (es) - ComediaporMovistarPlusPlus.es - Dec 9, 2024 (0 programs)\r\n    ERR: Request failed with status code 404\r\n  [12/372] movistarplus.es (es) - LaResistencia.es - Dec 10, 2024 (0 programs)\r\n    ERR: Request failed with status code 404\r\n  [13/372] movistarplus.es (es) - LaResistencia.es - Dec 9, 2024 (0 programs)\r\n    ERR: Request failed with status code 404\r\n```',
    closed_by: null,
    reactions: {
      url: 'https://api.github.com/repos/iptv-org/epg/issues/2498/reactions',
      total_count: 0,
      '+1': 0,
      '-1': 0,
      laugh: 0,
      hooray: 0,
      confused: 0,
      heart: 0,
      rocket: 0,
      eyes: 0
    },
    timeline_url: 'https://api.github.com/repos/iptv-org/epg/issues/2498/timeline',
    performed_via_github_app: null,
    state_reason: null
  },
  {
    url: 'https://api.github.com/repos/iptv-org/epg/issues/2445',
    repository_url: 'https://api.github.com/repos/iptv-org/epg',
    labels_url: 'https://api.github.com/repos/iptv-org/epg/issues/2445/labels{/name}',
    comments_url: 'https://api.github.com/repos/iptv-org/epg/issues/2445/comments',
    events_url: 'https://api.github.com/repos/iptv-org/epg/issues/2445/events',
    html_url: 'https://github.com/iptv-org/epg/issues/2445',
    id: 2567652015,
    node_id: 'I_kwDOFLVvtM6ZC0Kv',
    number: 2445,
    title: 'EPG from dishtv.in stopped with error code 404',
    user: {
      login: 'dheer99',
      id: 20639130,
      node_id: 'MDQ6VXNlcjIwNjM5MTMw',
      avatar_url: 'https://avatars.githubusercontent.com/u/20639130?v=4',
      gravatar_id: '',
      url: 'https://api.github.com/users/dheer99',
      html_url: 'https://github.com/dheer99',
      followers_url: 'https://api.github.com/users/dheer99/followers',
      following_url: 'https://api.github.com/users/dheer99/following{/other_user}',
      gists_url: 'https://api.github.com/users/dheer99/gists{/gist_id}',
      starred_url: 'https://api.github.com/users/dheer99/starred{/owner}{/repo}',
      subscriptions_url: 'https://api.github.com/users/dheer99/subscriptions',
      organizations_url: 'https://api.github.com/users/dheer99/orgs',
      repos_url: 'https://api.github.com/users/dheer99/repos',
      events_url: 'https://api.github.com/users/dheer99/events{/privacy}',
      received_events_url: 'https://api.github.com/users/dheer99/received_events',
      type: 'User',
      user_view_type: 'public',
      site_admin: false
    },
    labels: [
      {
        id: 4542348869,
        node_id: 'LA_kwDOFLVvtM8AAAABDr6-RQ',
        url: 'https://api.github.com/repos/iptv-org/epg/labels/broken%20guide',
        name: 'broken guide',
        color: 'eaeaea',
        default: false,
        description: "There's a problem with the guide"
      },
      {
        id: 7932710795,
        node_id: 'LA_kwDOFLVvtM8AAAAB2NOPiw',
        url: 'https://api.github.com/repos/iptv-org/epg/labels/status:down',
        name: 'status:down',
        color: 'df3a4a',
        default: false,
        description: "The guide doesn't work"
      }
    ],
    state: 'open',
    locked: false,
    assignee: null,
    assignees: [],
    milestone: null,
    comments: 2,
    created_at: '2024-10-05T04:30:52Z',
    updated_at: '2024-12-27T05:20:11Z',
    closed_at: null,
    author_association: 'NONE',
    active_lock_reason: null,
    body: '### Site\n\ndishtv.in\n\n### Description\n\nEPG from dishtv.in stopped with error code 404\r\n\r\n  [91/98] dishtv.in (en) - StarPlus.in - Oct 5, 2024 (0 programs)\r\n    ERR: Request failed with status code 404\r\n  [92/98] dishtv.in (en) - SET.in - Oct 6, 2024 (0 programs)\r\n    ERR: Request failed with status code 404\r\n  [93/98] dishtv.in (en) - ZeeCinema.in - Oct 6, 2024 (0 programs)\r\n    ERR: Request failed with status code 404\r\n  [94/98] dishtv.in (en) - SonySportsTen5.in - Oct 5, 2024 (0 programs)\r\n    ERR: Request failed with status code 404\r\n  [95/98] dishtv.in (en) - StarSports1.in - Oct 6, 2024 (0 programs)\r\n    ERR: Request failed with status code 404\r\n  [96/98] dishtv.in (en) - SET.in - Oct 5, 2024 (0 programs)\r\n    ERR: Request failed with status code 404\r\n  [97/98] dishtv.in (en) - SonySportsTen3.in - Oct 6, 2024 (0 programs)\r\n    ERR: Request failed with status code 404\r\n  [98/98] dishtv.in (en) - Colors.in - Oct 6, 2024 (0 programs)\r\n    ERR: Request failed with status code 404\r\n  done in 00h 00m 03s\r\n',
    closed_by: null,
    reactions: {
      url: 'https://api.github.com/repos/iptv-org/epg/issues/2445/reactions',
      total_count: 0,
      '+1': 0,
      '-1': 0,
      laugh: 0,
      hooray: 0,
      confused: 0,
      heart: 0,
      rocket: 0,
      eyes: 0
    },
    timeline_url: 'https://api.github.com/repos/iptv-org/epg/issues/2445/timeline',
    performed_via_github_app: null,
    state_reason: null
  },
  {
    url: 'https://api.github.com/repos/iptv-org/epg/issues/2339',
    repository_url: 'https://api.github.com/repos/iptv-org/epg',
    labels_url: 'https://api.github.com/repos/iptv-org/epg/issues/2339/labels{/name}',
    comments_url: 'https://api.github.com/repos/iptv-org/epg/issues/2339/comments',
    events_url: 'https://api.github.com/repos/iptv-org/epg/issues/2339/events',
    html_url: 'https://github.com/iptv-org/epg/issues/2339',
    id: 2172864415,
    node_id: 'I_kwDOFLVvtM6Bg0ef',
    number: 2339,
    title:
      'directv.com.ar and directv.com.uy not working ERR: Unexpected token \'<\', "<!DOCTYPE "... is not valid JSON',
    user: {
      login: 'razametal',
      id: 46631,
      node_id: 'MDQ6VXNlcjQ2NjMx',
      avatar_url: 'https://avatars.githubusercontent.com/u/46631?v=4',
      gravatar_id: '',
      url: 'https://api.github.com/users/razametal',
      html_url: 'https://github.com/razametal',
      followers_url: 'https://api.github.com/users/razametal/followers',
      following_url: 'https://api.github.com/users/razametal/following{/other_user}',
      gists_url: 'https://api.github.com/users/razametal/gists{/gist_id}',
      starred_url: 'https://api.github.com/users/razametal/starred{/owner}{/repo}',
      subscriptions_url: 'https://api.github.com/users/razametal/subscriptions',
      organizations_url: 'https://api.github.com/users/razametal/orgs',
      repos_url: 'https://api.github.com/users/razametal/repos',
      events_url: 'https://api.github.com/users/razametal/events{/privacy}',
      received_events_url: 'https://api.github.com/users/razametal/received_events',
      type: 'User',
      user_view_type: 'public',
      site_admin: false
    },
    labels: [
      {
        id: 4476686011,
        node_id: 'LA_kwDOFLVvtM8AAAABCtTOuw',
        url: 'https://api.github.com/repos/iptv-org/epg/labels/site:geoblocked',
        name: 'site:geoblocked',
        color: 'A05EBB',
        default: false,
        description: 'EPG website is geo-blocked'
      },
      {
        id: 4542348869,
        node_id: 'LA_kwDOFLVvtM8AAAABDr6-RQ',
        url: 'https://api.github.com/repos/iptv-org/epg/labels/broken%20guide',
        name: 'broken guide',
        color: 'eaeaea',
        default: false,
        description: "There's a problem with the guide"
      },
      {
        id: 7932710795,
        node_id: 'LA_kwDOFLVvtM8AAAAB2NOPiw',
        url: 'https://api.github.com/repos/iptv-org/epg/labels/status:down',
        name: 'status:down',
        color: 'df3a4a',
        default: false,
        description: "The guide doesn't work"
      }
    ],
    state: 'open',
    locked: false,
    assignee: null,
    assignees: [],
    milestone: null,
    comments: 0,
    created_at: '2024-03-07T03:23:38Z',
    updated_at: '2024-12-27T05:04:41Z',
    closed_at: null,
    author_association: 'NONE',
    active_lock_reason: null,
    body: '### Site\n\ndirectv.com.ar\n\n### Description\n\nGetting the following error after runing :\r\n\r\n npm run grab -- --site=directv.com.ar\r\n\r\n    ERR: Unexpected token \'<\', "<!DOCTYPE "... is not valid JSON\r\n  [30/814] directv.com.ar (es) - UniversalPremiereWest.us - Mar 7, 2024 (0 programs)\r\n    ERR: Unexpected token \'<\', "<!DOCTYPE "... is not valid JSON\r\n  [31/814] directv.com.ar (es) - UniversalPremiereWest.us - Mar 8, 2024 (0 programs)\r\n    ERR: Unexpected token \'<\', "<!DOCTYPE "... is not valid JSON\r\n\r\n\r\nSame situation with directv.com.uy',
    closed_by: null,
    reactions: {
      url: 'https://api.github.com/repos/iptv-org/epg/issues/2339/reactions',
      total_count: 0,
      '+1': 0,
      '-1': 0,
      laugh: 0,
      hooray: 0,
      confused: 0,
      heart: 0,
      rocket: 0,
      eyes: 0
    },
    timeline_url: 'https://api.github.com/repos/iptv-org/epg/issues/2339/timeline',
    performed_via_github_app: null,
    state_reason: null
  },
  {
    url: 'https://api.github.com/repos/iptv-org/epg/issues/2284',
    repository_url: 'https://api.github.com/repos/iptv-org/epg',
    labels_url: 'https://api.github.com/repos/iptv-org/epg/issues/2284/labels{/name}',
    comments_url: 'https://api.github.com/repos/iptv-org/epg/issues/2284/comments',
    events_url: 'https://api.github.com/repos/iptv-org/epg/issues/2284/events',
    html_url: 'https://github.com/iptv-org/epg/issues/2284',
    id: 2052254814,
    node_id: 'I_kwDOFLVvtM56Uuxe',
    number: 2284,
    title: 'Directv.com not working',
    user: {
      login: 'Deihmos',
      id: 14289123,
      node_id: 'MDQ6VXNlcjE0Mjg5MTIz',
      avatar_url: 'https://avatars.githubusercontent.com/u/14289123?v=4',
      gravatar_id: '',
      url: 'https://api.github.com/users/Deihmos',
      html_url: 'https://github.com/Deihmos',
      followers_url: 'https://api.github.com/users/Deihmos/followers',
      following_url: 'https://api.github.com/users/Deihmos/following{/other_user}',
      gists_url: 'https://api.github.com/users/Deihmos/gists{/gist_id}',
      starred_url: 'https://api.github.com/users/Deihmos/starred{/owner}{/repo}',
      subscriptions_url: 'https://api.github.com/users/Deihmos/subscriptions',
      organizations_url: 'https://api.github.com/users/Deihmos/orgs',
      repos_url: 'https://api.github.com/users/Deihmos/repos',
      events_url: 'https://api.github.com/users/Deihmos/events{/privacy}',
      received_events_url: 'https://api.github.com/users/Deihmos/received_events',
      type: 'User',
      user_view_type: 'public',
      site_admin: false
    },
    labels: [
      {
        id: 4542348869,
        node_id: 'LA_kwDOFLVvtM8AAAABDr6-RQ',
        url: 'https://api.github.com/repos/iptv-org/epg/labels/broken%20guide',
        name: 'broken guide',
        color: 'eaeaea',
        default: false,
        description: "There's a problem with the guide"
      },
      {
        id: 7932710795,
        node_id: 'LA_kwDOFLVvtM8AAAAB2NOPiw',
        url: 'https://api.github.com/repos/iptv-org/epg/labels/status:down',
        name: 'status:down',
        color: 'df3a4a',
        default: false,
        description: "The guide doesn't work"
      }
    ],
    state: 'open',
    locked: false,
    assignee: null,
    assignees: [],
    milestone: null,
    comments: 2,
    created_at: '2023-12-21T11:35:53Z',
    updated_at: '2024-12-27T05:03:58Z',
    closed_at: null,
    author_association: 'NONE',
    active_lock_reason: null,
    body: "### Site\n\ndirectv.com\n\n### Description\n\nThanks for this tool. I discovered it just today. \r\n\r\nDirectv.com isn't working for me. I get the following error:  ERR: Request failed with status code 404",
    closed_by: null,
    reactions: {
      url: 'https://api.github.com/repos/iptv-org/epg/issues/2284/reactions',
      total_count: 0,
      '+1': 0,
      '-1': 0,
      laugh: 0,
      hooray: 0,
      confused: 0,
      heart: 0,
      rocket: 0,
      eyes: 0
    },
    timeline_url: 'https://api.github.com/repos/iptv-org/epg/issues/2284/timeline',
    performed_via_github_app: null,
    state_reason: null
  },
  {
    url: 'https://api.github.com/repos/iptv-org/epg/issues/2273',
    repository_url: 'https://api.github.com/repos/iptv-org/epg',
    labels_url: 'https://api.github.com/repos/iptv-org/epg/issues/2273/labels{/name}',
    comments_url: 'https://api.github.com/repos/iptv-org/epg/issues/2273/comments',
    events_url: 'https://api.github.com/repos/iptv-org/epg/issues/2273/events',
    html_url: 'https://github.com/iptv-org/epg/issues/2273',
    id: 2022155805,
    node_id: 'I_kwDOFLVvtM54h6Yd',
    number: 2273,
    title: 'kan.org.il is broken',
    user: {
      login: 'TVKaista',
      id: 103857112,
      node_id: 'U_kgDOBjC72A',
      avatar_url: 'https://avatars.githubusercontent.com/u/103857112?v=4',
      gravatar_id: '',
      url: 'https://api.github.com/users/TVKaista',
      html_url: 'https://github.com/TVKaista',
      followers_url: 'https://api.github.com/users/TVKaista/followers',
      following_url: 'https://api.github.com/users/TVKaista/following{/other_user}',
      gists_url: 'https://api.github.com/users/TVKaista/gists{/gist_id}',
      starred_url: 'https://api.github.com/users/TVKaista/starred{/owner}{/repo}',
      subscriptions_url: 'https://api.github.com/users/TVKaista/subscriptions',
      organizations_url: 'https://api.github.com/users/TVKaista/orgs',
      repos_url: 'https://api.github.com/users/TVKaista/repos',
      events_url: 'https://api.github.com/users/TVKaista/events{/privacy}',
      received_events_url: 'https://api.github.com/users/TVKaista/received_events',
      type: 'User',
      user_view_type: 'public',
      site_admin: false
    },
    labels: [
      {
        id: 4542348869,
        node_id: 'LA_kwDOFLVvtM8AAAABDr6-RQ',
        url: 'https://api.github.com/repos/iptv-org/epg/labels/broken%20guide',
        name: 'broken guide',
        color: 'eaeaea',
        default: false,
        description: "There's a problem with the guide"
      },
      {
        id: 7932710795,
        node_id: 'LA_kwDOFLVvtM8AAAAB2NOPiw',
        url: 'https://api.github.com/repos/iptv-org/epg/labels/status:down',
        name: 'status:down',
        color: 'df3a4a',
        default: false,
        description: "The guide doesn't work"
      }
    ],
    state: 'open',
    locked: false,
    assignee: null,
    assignees: [],
    milestone: null,
    comments: 0,
    created_at: '2023-12-02T18:27:32Z',
    updated_at: '2024-12-27T05:03:00Z',
    closed_at: null,
    author_association: 'CONTRIBUTOR',
    active_lock_reason: null,
    body: '### Site\n\nkan.org.il\n\n### Description\n\n```\r\n> grab\r\n> npx tsx scripts/commands/epg/grab.ts --site=kan.org.il --output=kan.org.il.xml\r\n\r\nstarting...\r\nconfig:\r\n  output: kan.org.il.xml\r\n  maxConnections: 1\r\n  gzip: false\r\n  site: kan.org.il\r\nloading channels...\r\n  found 3 channel(s)\r\nrun #1:\r\n  [1/6] kan.org.il (ar) - Makan33.il - Dec 2, 2023 (0 programs)\r\n    ERR: Request failed with status code 404\r\n  [2/6] kan.org.il (ar) - Makan33.il - Dec 3, 2023 (0 programs)\r\n    ERR: Request failed with status code 404\r\n  [3/6] kan.org.il (he) - KanEducational.il - Dec 3, 2023 (0 programs)\r\n    ERR: Request failed with status code 404\r\n  [4/6] kan.org.il (he) - KanEducational.il - Dec 2, 2023 (0 programs)\r\n    ERR: Request failed with status code 404\r\n  [5/6] kan.org.il (he) - Kan11.il - Dec 3, 2023 (0 programs)\r\n    ERR: Request failed with status code 404\r\n  [6/6] kan.org.il (he) - Kan11.il - Dec 2, 2023 (0 programs)\r\n    ERR: Request failed with status code 404\r\n  done in 00h 00m 01s\r\n```',
    closed_by: null,
    reactions: {
      url: 'https://api.github.com/repos/iptv-org/epg/issues/2273/reactions',
      total_count: 0,
      '+1': 0,
      '-1': 0,
      laugh: 0,
      hooray: 0,
      confused: 0,
      heart: 0,
      rocket: 0,
      eyes: 0
    },
    timeline_url: 'https://api.github.com/repos/iptv-org/epg/issues/2273/timeline',
    performed_via_github_app: null,
    state_reason: null
  },
  {
    url: 'https://api.github.com/repos/iptv-org/epg/issues/2270',
    repository_url: 'https://api.github.com/repos/iptv-org/epg',
    labels_url: 'https://api.github.com/repos/iptv-org/epg/issues/2270/labels{/name}',
    comments_url: 'https://api.github.com/repos/iptv-org/epg/issues/2270/comments',
    events_url: 'https://api.github.com/repos/iptv-org/epg/issues/2270/events',
    html_url: 'https://github.com/iptv-org/epg/issues/2270',
    id: 2022018570,
    node_id: 'I_kwDOFLVvtM54hY4K',
    number: 2270,
    title: 'vivacom.bg is broken',
    user: {
      login: 'freearhey',
      id: 7253922,
      node_id: 'MDQ6VXNlcjcyNTM5MjI=',
      avatar_url: 'https://avatars.githubusercontent.com/u/7253922?v=4',
      gravatar_id: '',
      url: 'https://api.github.com/users/freearhey',
      html_url: 'https://github.com/freearhey',
      followers_url: 'https://api.github.com/users/freearhey/followers',
      following_url: 'https://api.github.com/users/freearhey/following{/other_user}',
      gists_url: 'https://api.github.com/users/freearhey/gists{/gist_id}',
      starred_url: 'https://api.github.com/users/freearhey/starred{/owner}{/repo}',
      subscriptions_url: 'https://api.github.com/users/freearhey/subscriptions',
      organizations_url: 'https://api.github.com/users/freearhey/orgs',
      repos_url: 'https://api.github.com/users/freearhey/repos',
      events_url: 'https://api.github.com/users/freearhey/events{/privacy}',
      received_events_url: 'https://api.github.com/users/freearhey/received_events',
      type: 'User',
      user_view_type: 'public',
      site_admin: false
    },
    labels: [
      {
        id: 4542348869,
        node_id: 'LA_kwDOFLVvtM8AAAABDr6-RQ',
        url: 'https://api.github.com/repos/iptv-org/epg/labels/broken%20guide',
        name: 'broken guide',
        color: 'eaeaea',
        default: false,
        description: "There's a problem with the guide"
      },
      {
        id: 7932710795,
        node_id: 'LA_kwDOFLVvtM8AAAAB2NOPiw',
        url: 'https://api.github.com/repos/iptv-org/epg/labels/status:down',
        name: 'status:down',
        color: 'df3a4a',
        default: false,
        description: "The guide doesn't work"
      }
    ],
    state: 'open',
    locked: false,
    assignee: null,
    assignees: [],
    milestone: null,
    comments: 0,
    created_at: '2023-12-02T12:16:22Z',
    updated_at: '2024-12-27T05:00:36Z',
    closed_at: null,
    author_association: 'COLLABORATOR',
    active_lock_reason: null,
    body: '### Site\n\nvivacom.bg\n\n### Description\n\n```sh\r\nnpm run grab -- --site=vivacom.bg\r\n\r\n> grab\r\n> npx tsx scripts/commands/epg/grab.ts --site=vivacom.bg\r\n\r\nstarting...\r\nconfig:\r\n  output: guide.xml\r\n  maxConnections: 1\r\n  gzip: false\r\n  site: vivacom.bg\r\nloading channels...\r\n  found 154 channel(s)\r\nrun #1:\r\n  [1/308] vivacom.bg (bg) - 24Kitchen.bg - Dec 2, 2023 (0 programs)\r\n  [2/308] vivacom.bg (bg) - 24Kitchen.bg - Dec 3, 2023 (0 programs)\r\n  [3/308] vivacom.bg (bg) - 78TV.bg - Dec 3, 2023 (0 programs)\r\n  [4/308] vivacom.bg (bg) - AlfaTV.bg - Dec 3, 2023 (0 programs)\r\n  [5/308] vivacom.bg (bg) - AXNEurope.gr - Dec 3, 2023 (0 programs)\r\n  [6/308] vivacom.bg (bg) - BNT3.bg - Dec 3, 2023 (0 programs)\r\n```',
    closed_by: null,
    reactions: {
      url: 'https://api.github.com/repos/iptv-org/epg/issues/2270/reactions',
      total_count: 0,
      '+1': 0,
      '-1': 0,
      laugh: 0,
      hooray: 0,
      confused: 0,
      heart: 0,
      rocket: 0,
      eyes: 0
    },
    timeline_url: 'https://api.github.com/repos/iptv-org/epg/issues/2270/timeline',
    performed_via_github_app: null,
    state_reason: null
  },
  {
    url: 'https://api.github.com/repos/iptv-org/epg/issues/2264',
    repository_url: 'https://api.github.com/repos/iptv-org/epg',
    labels_url: 'https://api.github.com/repos/iptv-org/epg/issues/2264/labels{/name}',
    comments_url: 'https://api.github.com/repos/iptv-org/epg/issues/2264/comments',
    events_url: 'https://api.github.com/repos/iptv-org/epg/issues/2264/events',
    html_url: 'https://github.com/iptv-org/epg/issues/2264',
    id: 2019407629,
    node_id: 'I_kwDOFLVvtM54XbcN',
    number: 2264,
    title: 'tva.tv is broken',
    user: {
      login: 'freearhey',
      id: 7253922,
      node_id: 'MDQ6VXNlcjcyNTM5MjI=',
      avatar_url: 'https://avatars.githubusercontent.com/u/7253922?v=4',
      gravatar_id: '',
      url: 'https://api.github.com/users/freearhey',
      html_url: 'https://github.com/freearhey',
      followers_url: 'https://api.github.com/users/freearhey/followers',
      following_url: 'https://api.github.com/users/freearhey/following{/other_user}',
      gists_url: 'https://api.github.com/users/freearhey/gists{/gist_id}',
      starred_url: 'https://api.github.com/users/freearhey/starred{/owner}{/repo}',
      subscriptions_url: 'https://api.github.com/users/freearhey/subscriptions',
      organizations_url: 'https://api.github.com/users/freearhey/orgs',
      repos_url: 'https://api.github.com/users/freearhey/repos',
      events_url: 'https://api.github.com/users/freearhey/events{/privacy}',
      received_events_url: 'https://api.github.com/users/freearhey/received_events',
      type: 'User',
      user_view_type: 'public',
      site_admin: false
    },
    labels: [
      {
        id: 4542348869,
        node_id: 'LA_kwDOFLVvtM8AAAABDr6-RQ',
        url: 'https://api.github.com/repos/iptv-org/epg/labels/broken%20guide',
        name: 'broken guide',
        color: 'eaeaea',
        default: false,
        description: "There's a problem with the guide"
      },
      {
        id: 7932710795,
        node_id: 'LA_kwDOFLVvtM8AAAAB2NOPiw',
        url: 'https://api.github.com/repos/iptv-org/epg/labels/status:down',
        name: 'status:down',
        color: 'df3a4a',
        default: false,
        description: "The guide doesn't work"
      }
    ],
    state: 'open',
    locked: false,
    assignee: null,
    assignees: [],
    milestone: null,
    comments: 0,
    created_at: '2023-11-30T20:00:18Z',
    updated_at: '2024-12-27T05:00:24Z',
    closed_at: null,
    author_association: 'COLLABORATOR',
    active_lock_reason: null,
    body: '### Site\n\ntva.tv\n\n### Description\n\n```sh\r\nnpm run grab -- --site=tva.tv\r\n\r\n> grab\r\n> npx tsx scripts/commands/epg/grab.ts --site=tva.tv\r\n\r\nstaring...\r\nconfig:\r\n  output: guide.xml\r\n  maxConnections: 1\r\n  gzip: false\r\n  site: tva.tv\r\nloading channels...\r\n  found 28 channel(s)\r\nrun #1:\r\n  [1/56] tva.tv (fa) - DocTV.ir - Nov 30, 2023 (0 programs)\r\n    ERR: Connection timeout\r\n  [2/56] tva.tv (fa) - DocTV.ir - Dec 1, 2023 (0 programs)\r\n    ERR: Connection timeout\r\n```',
    closed_by: null,
    reactions: {
      url: 'https://api.github.com/repos/iptv-org/epg/issues/2264/reactions',
      total_count: 0,
      '+1': 0,
      '-1': 0,
      laugh: 0,
      hooray: 0,
      confused: 0,
      heart: 0,
      rocket: 0,
      eyes: 0
    },
    timeline_url: 'https://api.github.com/repos/iptv-org/epg/issues/2264/timeline',
    performed_via_github_app: null,
    state_reason: null
  },
  {
    url: 'https://api.github.com/repos/iptv-org/epg/issues/2263',
    repository_url: 'https://api.github.com/repos/iptv-org/epg',
    labels_url: 'https://api.github.com/repos/iptv-org/epg/issues/2263/labels{/name}',
    comments_url: 'https://api.github.com/repos/iptv-org/epg/issues/2263/comments',
    events_url: 'https://api.github.com/repos/iptv-org/epg/issues/2263/events',
    html_url: 'https://github.com/iptv-org/epg/issues/2263',
    id: 2019376043,
    node_id: 'I_kwDOFLVvtM54XTur',
    number: 2263,
    title: 'tv.yettel.hu is broken',
    user: {
      login: 'freearhey',
      id: 7253922,
      node_id: 'MDQ6VXNlcjcyNTM5MjI=',
      avatar_url: 'https://avatars.githubusercontent.com/u/7253922?v=4',
      gravatar_id: '',
      url: 'https://api.github.com/users/freearhey',
      html_url: 'https://github.com/freearhey',
      followers_url: 'https://api.github.com/users/freearhey/followers',
      following_url: 'https://api.github.com/users/freearhey/following{/other_user}',
      gists_url: 'https://api.github.com/users/freearhey/gists{/gist_id}',
      starred_url: 'https://api.github.com/users/freearhey/starred{/owner}{/repo}',
      subscriptions_url: 'https://api.github.com/users/freearhey/subscriptions',
      organizations_url: 'https://api.github.com/users/freearhey/orgs',
      repos_url: 'https://api.github.com/users/freearhey/repos',
      events_url: 'https://api.github.com/users/freearhey/events{/privacy}',
      received_events_url: 'https://api.github.com/users/freearhey/received_events',
      type: 'User',
      user_view_type: 'public',
      site_admin: false
    },
    labels: [
      {
        id: 4542348869,
        node_id: 'LA_kwDOFLVvtM8AAAABDr6-RQ',
        url: 'https://api.github.com/repos/iptv-org/epg/labels/broken%20guide',
        name: 'broken guide',
        color: 'eaeaea',
        default: false,
        description: "There's a problem with the guide"
      },
      {
        id: 7932710795,
        node_id: 'LA_kwDOFLVvtM8AAAAB2NOPiw',
        url: 'https://api.github.com/repos/iptv-org/epg/labels/status:down',
        name: 'status:down',
        color: 'df3a4a',
        default: false,
        description: "The guide doesn't work"
      }
    ],
    state: 'open',
    locked: false,
    assignee: null,
    assignees: [],
    milestone: null,
    comments: 0,
    created_at: '2023-11-30T19:38:28Z',
    updated_at: '2024-12-27T04:59:14Z',
    closed_at: null,
    author_association: 'COLLABORATOR',
    active_lock_reason: null,
    body: '### Site\n\ntv.yettel.hu\n\n### Description\n\n```sh\r\nnpm run grab -- --site=tv.yettel.hu\r\n\r\n> grab\r\n> npx tsx scripts/commands/epg/grab.ts --site=tv.yettel.hu\r\n\r\nstaring...\r\nconfig:\r\n  output: guide.xml\r\n  maxConnections: 1\r\n  gzip: false\r\n  site: tv.yettel.hu\r\nloading channels...\r\n  found 74 channel(s)\r\nrun #1:\r\n  [1/148] tv.yettel.hu (en) - BBCNewsEurope.uk - Nov 30, 2023 (0 programs)\r\n    ERR: Client network socket disconnected before secure TLS connection was established\r\n  [2/148] tv.yettel.hu (en) - BBCNewsEurope.uk - Dec 1, 2023 (0 programs)\r\n    ERR: Client network socket disconnected before secure TLS connection was established\r\n```',
    closed_by: null,
    reactions: {
      url: 'https://api.github.com/repos/iptv-org/epg/issues/2263/reactions',
      total_count: 0,
      '+1': 0,
      '-1': 0,
      laugh: 0,
      hooray: 0,
      confused: 0,
      heart: 0,
      rocket: 0,
      eyes: 0
    },
    timeline_url: 'https://api.github.com/repos/iptv-org/epg/issues/2263/timeline',
    performed_via_github_app: null,
    state_reason: null
  },
  {
    url: 'https://api.github.com/repos/iptv-org/epg/issues/2257',
    repository_url: 'https://api.github.com/repos/iptv-org/epg',
    labels_url: 'https://api.github.com/repos/iptv-org/epg/issues/2257/labels{/name}',
    comments_url: 'https://api.github.com/repos/iptv-org/epg/issues/2257/comments',
    events_url: 'https://api.github.com/repos/iptv-org/epg/issues/2257/events',
    html_url: 'https://github.com/iptv-org/epg/issues/2257',
    id: 2011054011,
    node_id: 'I_kwDOFLVvtM533j-7',
    number: 2257,
    title: 'rtb.gov.bn is broken',
    user: {
      login: 'freearhey',
      id: 7253922,
      node_id: 'MDQ6VXNlcjcyNTM5MjI=',
      avatar_url: 'https://avatars.githubusercontent.com/u/7253922?v=4',
      gravatar_id: '',
      url: 'https://api.github.com/users/freearhey',
      html_url: 'https://github.com/freearhey',
      followers_url: 'https://api.github.com/users/freearhey/followers',
      following_url: 'https://api.github.com/users/freearhey/following{/other_user}',
      gists_url: 'https://api.github.com/users/freearhey/gists{/gist_id}',
      starred_url: 'https://api.github.com/users/freearhey/starred{/owner}{/repo}',
      subscriptions_url: 'https://api.github.com/users/freearhey/subscriptions',
      organizations_url: 'https://api.github.com/users/freearhey/orgs',
      repos_url: 'https://api.github.com/users/freearhey/repos',
      events_url: 'https://api.github.com/users/freearhey/events{/privacy}',
      received_events_url: 'https://api.github.com/users/freearhey/received_events',
      type: 'User',
      user_view_type: 'public',
      site_admin: false
    },
    labels: [
      {
        id: 4542348869,
        node_id: 'LA_kwDOFLVvtM8AAAABDr6-RQ',
        url: 'https://api.github.com/repos/iptv-org/epg/labels/broken%20guide',
        name: 'broken guide',
        color: 'eaeaea',
        default: false,
        description: "There's a problem with the guide"
      },
      {
        id: 7932710795,
        node_id: 'LA_kwDOFLVvtM8AAAAB2NOPiw',
        url: 'https://api.github.com/repos/iptv-org/epg/labels/status:down',
        name: 'status:down',
        color: 'df3a4a',
        default: false,
        description: "The guide doesn't work"
      }
    ],
    state: 'open',
    locked: false,
    assignee: null,
    assignees: [],
    milestone: null,
    comments: 0,
    created_at: '2023-11-26T14:02:13Z',
    updated_at: '2024-12-27T04:59:29Z',
    closed_at: null,
    author_association: 'COLLABORATOR',
    active_lock_reason: null,
    body: '### Site\n\nrtb.gov.bn\n\n### Description\n\n```sh\r\nnpm run grab -- --site=rtb.gov.bn\r\n\r\n> grab\r\n> npx tsx scripts/commands/epg/grab.ts --site=rtb.gov.bn\r\n\r\nstaring...\r\nconfig:\r\n  output: guide.xml\r\n  maxConnections: 1\r\n  gzip: false\r\n  site: rtb.gov.bn\r\nloading channels...\r\n  found 3 channel(s)\r\nrun #1:\r\n  [1/6] rtb.gov.bn (ms) - RTBAneka.bn - Nov 26, 2023 (0 programs)\r\n    ERR: read ECONNRESET\r\n  [2/6] rtb.gov.bn (ms) - RTBAneka.bn - Nov 27, 2023 (0 programs)\r\n    ERR: read ECONNRESET\r\n  [3/6] rtb.gov.bn (ms) - RTBPerdana.bn - Nov 27, 2023 (0 programs)\r\n    ERR: read ECONNRESET\r\n```\r\n\r\nThere is no link to the guide on the website at the moment either: https://www.rtb.gov.bn/SitePages/Programme%20Guide.aspx',
    closed_by: null,
    reactions: {
      url: 'https://api.github.com/repos/iptv-org/epg/issues/2257/reactions',
      total_count: 0,
      '+1': 0,
      '-1': 0,
      laugh: 0,
      hooray: 0,
      confused: 0,
      heart: 0,
      rocket: 0,
      eyes: 0
    },
    timeline_url: 'https://api.github.com/repos/iptv-org/epg/issues/2257/timeline',
    performed_via_github_app: null,
    state_reason: null
  },
  {
    url: 'https://api.github.com/repos/iptv-org/epg/issues/2255',
    repository_url: 'https://api.github.com/repos/iptv-org/epg',
    labels_url: 'https://api.github.com/repos/iptv-org/epg/issues/2255/labels{/name}',
    comments_url: 'https://api.github.com/repos/iptv-org/epg/issues/2255/comments',
    events_url: 'https://api.github.com/repos/iptv-org/epg/issues/2255/events',
    html_url: 'https://github.com/iptv-org/epg/issues/2255',
    id: 2011043202,
    node_id: 'I_kwDOFLVvtM533hWC',
    number: 2255,
    title: 'rev.bs is broken',
    user: {
      login: 'freearhey',
      id: 7253922,
      node_id: 'MDQ6VXNlcjcyNTM5MjI=',
      avatar_url: 'https://avatars.githubusercontent.com/u/7253922?v=4',
      gravatar_id: '',
      url: 'https://api.github.com/users/freearhey',
      html_url: 'https://github.com/freearhey',
      followers_url: 'https://api.github.com/users/freearhey/followers',
      following_url: 'https://api.github.com/users/freearhey/following{/other_user}',
      gists_url: 'https://api.github.com/users/freearhey/gists{/gist_id}',
      starred_url: 'https://api.github.com/users/freearhey/starred{/owner}{/repo}',
      subscriptions_url: 'https://api.github.com/users/freearhey/subscriptions',
      organizations_url: 'https://api.github.com/users/freearhey/orgs',
      repos_url: 'https://api.github.com/users/freearhey/repos',
      events_url: 'https://api.github.com/users/freearhey/events{/privacy}',
      received_events_url: 'https://api.github.com/users/freearhey/received_events',
      type: 'User',
      user_view_type: 'public',
      site_admin: false
    },
    labels: [
      {
        id: 4542348869,
        node_id: 'LA_kwDOFLVvtM8AAAABDr6-RQ',
        url: 'https://api.github.com/repos/iptv-org/epg/labels/broken%20guide',
        name: 'broken guide',
        color: 'eaeaea',
        default: false,
        description: "There's a problem with the guide"
      },
      {
        id: 7932710795,
        node_id: 'LA_kwDOFLVvtM8AAAAB2NOPiw',
        url: 'https://api.github.com/repos/iptv-org/epg/labels/status:down',
        name: 'status:down',
        color: 'df3a4a',
        default: false,
        description: "The guide doesn't work"
      }
    ],
    state: 'open',
    locked: false,
    assignee: null,
    assignees: [],
    milestone: null,
    comments: 1,
    created_at: '2023-11-26T13:31:22Z',
    updated_at: '2024-12-27T22:02:28Z',
    closed_at: null,
    author_association: 'COLLABORATOR',
    active_lock_reason: null,
    body: '### Site\n\nrev.bs\n\n### Description\n\n```sh\r\nnpm run grab -- --site=rev.bs\r\n\r\n> grab\r\n> npx tsx scripts/commands/epg/grab.ts --site=rev.bs\r\n\r\nstaring...\r\nconfig:\r\n  output: guide.xml\r\n  maxConnections: 1\r\n  gzip: false\r\n  site: rev.bs\r\nloading channels...\r\n  found 179 channel(s)\r\nrun #1:\r\n  [1/358] rev.bs (en) - 3ABNEnglish.us - Nov 26, 2023 (0 programs)\r\n  [2/358] rev.bs (en) - 3ABNEnglish.us - Nov 27, 2023 (0 programs)\r\n  [3/358] rev.bs (en) - AEEast.us - Nov 27, 2023 (0 programs)\r\n  [4/358] rev.bs (en) - AMCEast.us - Nov 27, 2023 (0 programs)\r\n```\r\n---\r\n\r\n```json\r\n{\r\n\t"status": "OK",\r\n\t"data": {\r\n\t\t"schedule": [],\r\n\t\t"dateTime": {\r\n\t\t\t"date": "2023-11-27",\r\n\t\t\t"page": 0\r\n\t\t},\r\n\t\t"runtimes": [\r\n\t\t\t{\r\n\t\t\t\t"Rev class loaded": 1700899490.604637\r\n\t\t\t},\r\n\t\t\t{\r\n\t\t\t\t"TVGuide Class Loaded": 1700899490.638891\r\n\t\t\t},\r\n\t\t\t{\r\n\t\t\t\t"Validated form": 1700899490.640116\r\n\t\t\t},\r\n\t\t\t{\r\n\t\t\t\t"Pulled schedules": 1700899490.642099\r\n\t\t\t}\r\n\t\t]\r\n\t}\r\n}\r\n```\r\n\r\nhttps://www.rev.bs/wp-content/uploads/tv-guide/2023-11-27_0.json\r\n\r\n---\r\n\r\n<img width="1003" alt="image" src="https://github.com/iptv-org/epg/assets/7253922/58fbaec4-e73f-408e-8d02-d1feff150699">\r\n\r\nhttps://www.rev.bs/tv-guide-404/',
    closed_by: null,
    reactions: {
      url: 'https://api.github.com/repos/iptv-org/epg/issues/2255/reactions',
      total_count: 0,
      '+1': 0,
      '-1': 0,
      laugh: 0,
      hooray: 0,
      confused: 0,
      heart: 0,
      rocket: 0,
      eyes: 0
    },
    timeline_url: 'https://api.github.com/repos/iptv-org/epg/issues/2255/timeline',
    performed_via_github_app: null,
    state_reason: null
  },
  {
    url: 'https://api.github.com/repos/iptv-org/epg/issues/2241',
    repository_url: 'https://api.github.com/repos/iptv-org/epg',
    labels_url: 'https://api.github.com/repos/iptv-org/epg/issues/2241/labels{/name}',
    comments_url: 'https://api.github.com/repos/iptv-org/epg/issues/2241/comments',
    events_url: 'https://api.github.com/repos/iptv-org/epg/issues/2241/events',
    html_url: 'https://github.com/iptv-org/epg/issues/2241',
    id: 2002096969,
    node_id: 'I_kwDOFLVvtM53VZNJ',
    number: 2241,
    title: 'm.tv.sms.cz is broken',
    user: {
      login: 'freearhey',
      id: 7253922,
      node_id: 'MDQ6VXNlcjcyNTM5MjI=',
      avatar_url: 'https://avatars.githubusercontent.com/u/7253922?v=4',
      gravatar_id: '',
      url: 'https://api.github.com/users/freearhey',
      html_url: 'https://github.com/freearhey',
      followers_url: 'https://api.github.com/users/freearhey/followers',
      following_url: 'https://api.github.com/users/freearhey/following{/other_user}',
      gists_url: 'https://api.github.com/users/freearhey/gists{/gist_id}',
      starred_url: 'https://api.github.com/users/freearhey/starred{/owner}{/repo}',
      subscriptions_url: 'https://api.github.com/users/freearhey/subscriptions',
      organizations_url: 'https://api.github.com/users/freearhey/orgs',
      repos_url: 'https://api.github.com/users/freearhey/repos',
      events_url: 'https://api.github.com/users/freearhey/events{/privacy}',
      received_events_url: 'https://api.github.com/users/freearhey/received_events',
      type: 'User',
      user_view_type: 'public',
      site_admin: false
    },
    labels: [
      {
        id: 4542348869,
        node_id: 'LA_kwDOFLVvtM8AAAABDr6-RQ',
        url: 'https://api.github.com/repos/iptv-org/epg/labels/broken%20guide',
        name: 'broken guide',
        color: 'eaeaea',
        default: false,
        description: "There's a problem with the guide"
      },
      {
        id: 7932710795,
        node_id: 'LA_kwDOFLVvtM8AAAAB2NOPiw',
        url: 'https://api.github.com/repos/iptv-org/epg/labels/status:down',
        name: 'status:down',
        color: 'df3a4a',
        default: false,
        description: "The guide doesn't work"
      }
    ],
    state: 'open',
    locked: false,
    assignee: null,
    assignees: [],
    milestone: null,
    comments: 4,
    created_at: '2023-11-20T12:28:47Z',
    updated_at: '2024-12-27T04:58:41Z',
    closed_at: null,
    author_association: 'COLLABORATOR',
    active_lock_reason: null,
    body: '### Site\n\nm.tv.sms.cz\n\n### Description\n\n```sh\r\nnpm run grab -- --site=m.tv.sms.cz\r\n\r\n> grab\r\n> npx tsx scripts/commands/epg/grab.ts --site=m.tv.sms.cz\r\n\r\nstaring...\r\nconfig:\r\n  output: guide.xml\r\n  maxConnections: 1\r\n  gzip: false\r\n  site: m.tv.sms.cz\r\nloading channels...\r\n  found 525 channel(s)\r\nrun #1:\r\n  [1/1050] m.tv.sms.cz (bs) - BNTV.ba - Nov 20, 2023 (0 programs)\r\n    ERR: write EPROTO C04D101B01000000:error:0A000172:SSL routines:tls12_check_peer_sigalg:wrong signature type:ssl/t1_lib.c:1594:\r\n\r\n  [2/1050] m.tv.sms.cz (bs) - BNTV.ba - Nov 21, 2023 (0 programs)\r\n    ERR: write EPROTO C04D101B01000000:error:0A000172:SSL routines:tls12_check_peer_sigalg:wrong signature type:ssl/t1_lib.c:1594:\r\n\r\n  [3/1050] m.tv.sms.cz (cs) - AMC.cz - Nov 21, 2023 (0 programs)\r\n    ERR: write EPROTO C04D101B01000000:error:0A000172:SSL routines:tls12_check_peer_sigalg:wrong signature type:ssl/t1_lib.c:1594:\r\n```\r\n\r\nhttps://check-host.net/check-report/135d7e05kb9d',
    closed_by: null,
    reactions: {
      url: 'https://api.github.com/repos/iptv-org/epg/issues/2241/reactions',
      total_count: 0,
      '+1': 0,
      '-1': 0,
      laugh: 0,
      hooray: 0,
      confused: 0,
      heart: 0,
      rocket: 0,
      eyes: 0
    },
    timeline_url: 'https://api.github.com/repos/iptv-org/epg/issues/2241/timeline',
    performed_via_github_app: null,
    state_reason: null
  },
  {
    url: 'https://api.github.com/repos/iptv-org/epg/issues/2240',
    repository_url: 'https://api.github.com/repos/iptv-org/epg',
    labels_url: 'https://api.github.com/repos/iptv-org/epg/issues/2240/labels{/name}',
    comments_url: 'https://api.github.com/repos/iptv-org/epg/issues/2240/comments',
    events_url: 'https://api.github.com/repos/iptv-org/epg/issues/2240/events',
    html_url: 'https://github.com/iptv-org/epg/issues/2240',
    id: 2001847449,
    node_id: 'I_kwDOFLVvtM53UcSZ',
    number: 2240,
    title: 'kplus.vn is broken',
    user: {
      login: 'freearhey',
      id: 7253922,
      node_id: 'MDQ6VXNlcjcyNTM5MjI=',
      avatar_url: 'https://avatars.githubusercontent.com/u/7253922?v=4',
      gravatar_id: '',
      url: 'https://api.github.com/users/freearhey',
      html_url: 'https://github.com/freearhey',
      followers_url: 'https://api.github.com/users/freearhey/followers',
      following_url: 'https://api.github.com/users/freearhey/following{/other_user}',
      gists_url: 'https://api.github.com/users/freearhey/gists{/gist_id}',
      starred_url: 'https://api.github.com/users/freearhey/starred{/owner}{/repo}',
      subscriptions_url: 'https://api.github.com/users/freearhey/subscriptions',
      organizations_url: 'https://api.github.com/users/freearhey/orgs',
      repos_url: 'https://api.github.com/users/freearhey/repos',
      events_url: 'https://api.github.com/users/freearhey/events{/privacy}',
      received_events_url: 'https://api.github.com/users/freearhey/received_events',
      type: 'User',
      user_view_type: 'public',
      site_admin: false
    },
    labels: [
      {
        id: 4542348869,
        node_id: 'LA_kwDOFLVvtM8AAAABDr6-RQ',
        url: 'https://api.github.com/repos/iptv-org/epg/labels/broken%20guide',
        name: 'broken guide',
        color: 'eaeaea',
        default: false,
        description: "There's a problem with the guide"
      },
      {
        id: 7932710795,
        node_id: 'LA_kwDOFLVvtM8AAAAB2NOPiw',
        url: 'https://api.github.com/repos/iptv-org/epg/labels/status:down',
        name: 'status:down',
        color: 'df3a4a',
        default: false,
        description: "The guide doesn't work"
      }
    ],
    state: 'open',
    locked: false,
    assignee: null,
    assignees: [],
    milestone: null,
    comments: 0,
    created_at: '2023-11-20T10:19:23Z',
    updated_at: '2024-12-27T04:57:49Z',
    closed_at: null,
    author_association: 'COLLABORATOR',
    active_lock_reason: null,
    body: '### Site\n\nkplus.vn\n\n### Description\n\n```sh\r\nnpm run grab -- --site=kplus.vn\r\n\r\n> grab\r\n> npx tsx scripts/commands/epg/grab.ts --site=kplus.vn\r\n\r\nstaring...\r\nconfig:\r\n  output: guide.xml\r\n  maxConnections: 1\r\n  gzip: false\r\n  site: kplus.vn\r\nloading channels...\r\n  found 26 channel(s)\r\nrun #1:\r\n  [1/52] kplus.vn (vi) - AsianFoodNetwork.sg - Nov 20, 2023 (0 programs)\r\n  [2/52] kplus.vn (vi) - AsianFoodNetwork.sg - Nov 21, 2023 (0 programs)\r\n  [3/52] kplus.vn (vi) - AXN.vn - Nov 21, 2023 (0 programs)\r\n  [4/52] kplus.vn (vi) - DiscoveryChannelSoutheastAsia.sg - Nov 21, 2023 (0 programs)\r\n```\r\n\r\nThe site also currently does not display the guide:\r\n<img width="420" alt="image" src="https://github.com/iptv-org/epg/assets/7253922/b1920181-9aab-41e4-bfd4-dbfbcaf6648e">\r\nhttps://www.kplus.vn/highlights/broadcast-schedule',
    closed_by: null,
    reactions: {
      url: 'https://api.github.com/repos/iptv-org/epg/issues/2240/reactions',
      total_count: 0,
      '+1': 0,
      '-1': 0,
      laugh: 0,
      hooray: 0,
      confused: 0,
      heart: 0,
      rocket: 0,
      eyes: 0
    },
    timeline_url: 'https://api.github.com/repos/iptv-org/epg/issues/2240/timeline',
    performed_via_github_app: null,
    state_reason: null
  },
  {
    url: 'https://api.github.com/repos/iptv-org/epg/issues/2239',
    repository_url: 'https://api.github.com/repos/iptv-org/epg',
    labels_url: 'https://api.github.com/repos/iptv-org/epg/issues/2239/labels{/name}',
    comments_url: 'https://api.github.com/repos/iptv-org/epg/issues/2239/comments',
    events_url: 'https://api.github.com/repos/iptv-org/epg/issues/2239/events',
    html_url: 'https://github.com/iptv-org/epg/issues/2239',
    id: 2000457187,
    node_id: 'I_kwDOFLVvtM53PI3j',
    number: 2239,
    title: 'comteco.com.bo is broken',
    user: {
      login: 'freearhey',
      id: 7253922,
      node_id: 'MDQ6VXNlcjcyNTM5MjI=',
      avatar_url: 'https://avatars.githubusercontent.com/u/7253922?v=4',
      gravatar_id: '',
      url: 'https://api.github.com/users/freearhey',
      html_url: 'https://github.com/freearhey',
      followers_url: 'https://api.github.com/users/freearhey/followers',
      following_url: 'https://api.github.com/users/freearhey/following{/other_user}',
      gists_url: 'https://api.github.com/users/freearhey/gists{/gist_id}',
      starred_url: 'https://api.github.com/users/freearhey/starred{/owner}{/repo}',
      subscriptions_url: 'https://api.github.com/users/freearhey/subscriptions',
      organizations_url: 'https://api.github.com/users/freearhey/orgs',
      repos_url: 'https://api.github.com/users/freearhey/repos',
      events_url: 'https://api.github.com/users/freearhey/events{/privacy}',
      received_events_url: 'https://api.github.com/users/freearhey/received_events',
      type: 'User',
      user_view_type: 'public',
      site_admin: false
    },
    labels: [
      {
        id: 4542348869,
        node_id: 'LA_kwDOFLVvtM8AAAABDr6-RQ',
        url: 'https://api.github.com/repos/iptv-org/epg/labels/broken%20guide',
        name: 'broken guide',
        color: 'eaeaea',
        default: false,
        description: "There's a problem with the guide"
      },
      {
        id: 7932710795,
        node_id: 'LA_kwDOFLVvtM8AAAAB2NOPiw',
        url: 'https://api.github.com/repos/iptv-org/epg/labels/status:down',
        name: 'status:down',
        color: 'df3a4a',
        default: false,
        description: "The guide doesn't work"
      }
    ],
    state: 'open',
    locked: false,
    assignee: null,
    assignees: [],
    milestone: null,
    comments: 3,
    created_at: '2023-11-18T15:03:48Z',
    updated_at: '2024-12-27T21:25:41Z',
    closed_at: null,
    author_association: 'COLLABORATOR',
    active_lock_reason: null,
    body: '### Site\n\ncomteco.com.bo\n\n### Description\n\n```sh\r\nnpm run grab -- --site=comteco.com.bo\r\n\r\n> grab\r\n> npx tsx scripts/commands/epg/grab.ts --site=comteco.com.bo\r\n\r\nstaring...\r\nconfig:\r\n  output: guide.xml\r\n  maxConnections: 1\r\n  gzip: false\r\n  site: comteco.com.bo\r\nloading channels...\r\n  found 72 channel(s)\r\nrun #1:\r\n  [1/144] comteco.com.bo (es) - AbyaYalaTV.bo - Nov 18, 2023 (0 programs)\r\n  [2/144] comteco.com.bo (es) - AbyaYalaTV.bo - Nov 19, 2023 (0 programs)\r\n  [3/144] comteco.com.bo (es) - AEPanregional.us - Nov 19, 2023 (0 programs)\r\n  [4/144] comteco.com.bo (es) - AnimalPlanetLatinAmerica.us - Nov 19, 2023 (0 programs)\r\n  [5/144] comteco.com.bo (es) - BoliviaTV72.bo - Nov 19, 2023 (0 programs)\r\n```\r\n\r\nhttps://comteco.com.bo/pages/canales-y-programacion-tv/paquete-oro/ABYA%20YALA\r\n<img width="547" alt="image" src="https://github.com/iptv-org/epg/assets/7253922/a987cb02-61f2-41ba-b5d4-97bd4a62b1c6">',
    closed_by: null,
    reactions: {
      url: 'https://api.github.com/repos/iptv-org/epg/issues/2239/reactions',
      total_count: 0,
      '+1': 0,
      '-1': 0,
      laugh: 0,
      hooray: 0,
      confused: 0,
      heart: 0,
      rocket: 0,
      eyes: 0
    },
    timeline_url: 'https://api.github.com/repos/iptv-org/epg/issues/2239/timeline',
    performed_via_github_app: null,
    state_reason: null
  },
  {
    url: 'https://api.github.com/repos/iptv-org/epg/issues/2237',
    repository_url: 'https://api.github.com/repos/iptv-org/epg',
    labels_url: 'https://api.github.com/repos/iptv-org/epg/issues/2237/labels{/name}',
    comments_url: 'https://api.github.com/repos/iptv-org/epg/issues/2237/comments',
    events_url: 'https://api.github.com/repos/iptv-org/epg/issues/2237/events',
    html_url: 'https://github.com/iptv-org/epg/issues/2237',
    id: 2000349577,
    node_id: 'I_kwDOFLVvtM53OumJ',
    number: 2237,
    title: 'canalplus-haiti.com is broken',
    user: {
      login: 'freearhey',
      id: 7253922,
      node_id: 'MDQ6VXNlcjcyNTM5MjI=',
      avatar_url: 'https://avatars.githubusercontent.com/u/7253922?v=4',
      gravatar_id: '',
      url: 'https://api.github.com/users/freearhey',
      html_url: 'https://github.com/freearhey',
      followers_url: 'https://api.github.com/users/freearhey/followers',
      following_url: 'https://api.github.com/users/freearhey/following{/other_user}',
      gists_url: 'https://api.github.com/users/freearhey/gists{/gist_id}',
      starred_url: 'https://api.github.com/users/freearhey/starred{/owner}{/repo}',
      subscriptions_url: 'https://api.github.com/users/freearhey/subscriptions',
      organizations_url: 'https://api.github.com/users/freearhey/orgs',
      repos_url: 'https://api.github.com/users/freearhey/repos',
      events_url: 'https://api.github.com/users/freearhey/events{/privacy}',
      received_events_url: 'https://api.github.com/users/freearhey/received_events',
      type: 'User',
      user_view_type: 'public',
      site_admin: false
    },
    labels: [
      {
        id: 4542348869,
        node_id: 'LA_kwDOFLVvtM8AAAABDr6-RQ',
        url: 'https://api.github.com/repos/iptv-org/epg/labels/broken%20guide',
        name: 'broken guide',
        color: 'eaeaea',
        default: false,
        description: "There's a problem with the guide"
      },
      {
        id: 7932710795,
        node_id: 'LA_kwDOFLVvtM8AAAAB2NOPiw',
        url: 'https://api.github.com/repos/iptv-org/epg/labels/status:down',
        name: 'status:down',
        color: 'df3a4a',
        default: false,
        description: "The guide doesn't work"
      }
    ],
    state: 'open',
    locked: false,
    assignee: null,
    assignees: [],
    milestone: null,
    comments: 0,
    created_at: '2023-11-18T09:46:29Z',
    updated_at: '2024-12-27T04:57:02Z',
    closed_at: null,
    author_association: 'COLLABORATOR',
    active_lock_reason: null,
    body: '### Site\n\ncanalplus-haiti.com\n\n### Description\n\n```sh\r\nnpm run grab -- --site=canalplus-haiti.com\r\n\r\n> grab\r\n> npx tsx scripts/commands/epg/grab.ts --site=canalplus-haiti.com\r\n\r\nstaring...\r\nconfig:\r\n  output: guide.xml\r\n  maxConnections: 1\r\n  gzip: false\r\n  site: canalplus-haiti.com\r\nloading channels...\r\n  found 111 channel(s)\r\nrun #1:\r\n  [1/222] canalplus-haiti.com (fr) - 13emeRue.fr - Nov 18, 2023 (0 programs)\r\n    ERR: Request failed with status code 403\r\n  [2/222] canalplus-haiti.com (fr) - 13emeRue.fr - Nov 19, 2023 (0 programs)\r\n    ERR: Request failed with status code 403\r\n  [3/222] canalplus-haiti.com (fr) - ZoukTV.mq - Nov 19, 2023 (0 programs)\r\n    ERR: Request failed with status code 403\r\n  [4/222] canalplus-haiti.com (fr) - ZoukTV.mq - Nov 18, 2023 (0 programs)\r\n    ERR: Request failed with status code 403\r\n```\r\n\r\nhttps://check-host.net/check-report/134fc56bk333',
    closed_by: null,
    reactions: {
      url: 'https://api.github.com/repos/iptv-org/epg/issues/2237/reactions',
      total_count: 0,
      '+1': 0,
      '-1': 0,
      laugh: 0,
      hooray: 0,
      confused: 0,
      heart: 0,
      rocket: 0,
      eyes: 0
    },
    timeline_url: 'https://api.github.com/repos/iptv-org/epg/issues/2237/timeline',
    performed_via_github_app: null,
    state_reason: null
  },
  {
    url: 'https://api.github.com/repos/iptv-org/epg/issues/2173',
    repository_url: 'https://api.github.com/repos/iptv-org/epg',
    labels_url: 'https://api.github.com/repos/iptv-org/epg/issues/2173/labels{/name}',
    comments_url: 'https://api.github.com/repos/iptv-org/epg/issues/2173/comments',
    events_url: 'https://api.github.com/repos/iptv-org/epg/issues/2173/events',
    html_url: 'https://github.com/iptv-org/epg/issues/2173',
    id: 1903824500,
    node_id: 'I_kwDOFLVvtM5xeg50',
    number: 2173,
    title: 'hd-plus.de - 0 programs on all channels',
    user: {
      login: 'x011',
      id: 4313821,
      node_id: 'MDQ6VXNlcjQzMTM4MjE=',
      avatar_url: 'https://avatars.githubusercontent.com/u/4313821?v=4',
      gravatar_id: '',
      url: 'https://api.github.com/users/x011',
      html_url: 'https://github.com/x011',
      followers_url: 'https://api.github.com/users/x011/followers',
      following_url: 'https://api.github.com/users/x011/following{/other_user}',
      gists_url: 'https://api.github.com/users/x011/gists{/gist_id}',
      starred_url: 'https://api.github.com/users/x011/starred{/owner}{/repo}',
      subscriptions_url: 'https://api.github.com/users/x011/subscriptions',
      organizations_url: 'https://api.github.com/users/x011/orgs',
      repos_url: 'https://api.github.com/users/x011/repos',
      events_url: 'https://api.github.com/users/x011/events{/privacy}',
      received_events_url: 'https://api.github.com/users/x011/received_events',
      type: 'User',
      user_view_type: 'public',
      site_admin: false
    },
    labels: [
      {
        id: 4542348869,
        node_id: 'LA_kwDOFLVvtM8AAAABDr6-RQ',
        url: 'https://api.github.com/repos/iptv-org/epg/labels/broken%20guide',
        name: 'broken guide',
        color: 'eaeaea',
        default: false,
        description: "There's a problem with the guide"
      },
      {
        id: 7932710795,
        node_id: 'LA_kwDOFLVvtM8AAAAB2NOPiw',
        url: 'https://api.github.com/repos/iptv-org/epg/labels/status:down',
        name: 'status:down',
        color: 'df3a4a',
        default: false,
        description: "The guide doesn't work"
      }
    ],
    state: 'open',
    locked: false,
    assignee: null,
    assignees: [],
    milestone: null,
    comments: 1,
    created_at: '2023-09-19T22:45:56Z',
    updated_at: '2024-12-27T04:54:11Z',
    closed_at: null,
    author_association: 'NONE',
    active_lock_reason: null,
    body: '### Site\r\n\r\nhd-plus.de\r\n\r\n### Description\r\n\r\nAll channels on hd-plus.de have 0 programs:\r\n```\r\n[1/60] hd-plus.de - 123tv.de - Sep 19, 2023 (0 programs)\r\n[2/60] hd-plus.de - 123tv.de - Sep 20, 2023 (0 programs)\r\n[3/60] hd-plus.de - ZDF.de - Sep 20, 2023 (0 programs)\r\n[4/60] hd-plus.de - ZDF.de - Sep 19, 2023 (0 programs)\r\n...\r\n```',
    closed_by: null,
    reactions: {
      url: 'https://api.github.com/repos/iptv-org/epg/issues/2173/reactions',
      total_count: 6,
      '+1': 6,
      '-1': 0,
      laugh: 0,
      hooray: 0,
      confused: 0,
      heart: 0,
      rocket: 0,
      eyes: 0
    },
    timeline_url: 'https://api.github.com/repos/iptv-org/epg/issues/2173/timeline',
    performed_via_github_app: null,
    state_reason: null
  }
]
