export default [
  {
    url: 'https://api.github.com/repos/iptv-org/epg/issues/2543',
    repository_url: 'https://api.github.com/repos/iptv-org/epg',
    labels_url: 'https://api.github.com/repos/iptv-org/epg/issues/2543/labels{/name}',
    comments_url: 'https://api.github.com/repos/iptv-org/epg/issues/2543/comments',
    events_url: 'https://api.github.com/repos/iptv-org/epg/issues/2543/events',
    html_url: 'https://github.com/iptv-org/epg/issues/2543',
    id: 2759693796,
    node_id: 'I_kwDOFLVvtM6kfZXk',
    number: 2543,
    title: 'flixed.io is downloding old programming',
    user: {
      login: 'SiWafer',
      id: 10903014,
      node_id: 'MDQ6VXNlcjEwOTAzMDE0',
      avatar_url: 'https://avatars.githubusercontent.com/u/10903014?v=4',
      gravatar_id: '',
      url: 'https://api.github.com/users/SiWafer',
      html_url: 'https://github.com/SiWafer',
      followers_url: 'https://api.github.com/users/SiWafer/followers',
      following_url: 'https://api.github.com/users/SiWafer/following{/other_user}',
      gists_url: 'https://api.github.com/users/SiWafer/gists{/gist_id}',
      starred_url: 'https://api.github.com/users/SiWafer/starred{/owner}{/repo}',
      subscriptions_url: 'https://api.github.com/users/SiWafer/subscriptions',
      organizations_url: 'https://api.github.com/users/SiWafer/orgs',
      repos_url: 'https://api.github.com/users/SiWafer/repos',
      events_url: 'https://api.github.com/users/SiWafer/events{/privacy}',
      received_events_url: 'https://api.github.com/users/SiWafer/received_events',
      type: 'User',
      user_view_type: 'public',
      site_admin: false
    },
    labels: [
      {
        id: 4542348869,
        node_id: 'LA_kwDOFLVvtM8AAAABDr6-RQ',
        url: 'https://api.github.com/repos/iptv-org/epg/labels/broken%20guide',
        name: 'broken guide',
        color: 'eaeaea',
        default: false,
        description: "There's a problem with the guide"
      },
      {
        id: 7932710318,
        node_id: 'LA_kwDOFLVvtM8AAAAB2NONrg',
        url: 'https://api.github.com/repos/iptv-org/epg/labels/status:warning',
        name: 'status:warning',
        color: 'fbca06',
        default: false,
        description: 'The guide downloads, but contains errors'
      }
    ],
    state: 'open',
    locked: false,
    assignee: null,
    assignees: [],
    milestone: null,
    comments: 0,
    created_at: '2024-12-26T12:09:43Z',
    updated_at: '2024-12-27T05:29:58Z',
    closed_at: null,
    author_association: 'NONE',
    active_lock_reason: null,
    body: '### Describe your issue\r\n\r\nJust ran and updated, and seems the output is loading old programming and it also is not complete\r\n\r\nExample is Bravo channel\r\n\r\n```\r\nepg@rpi:~/epg$ npm run grab --- --site=flixed.io --maxConnections=10  -o "flixed.xml"\r\n\r\n> grab\r\n> npx tsx scripts/commands/epg/grab.ts --site=flixed.io --maxConnections=10 -o flixed.xml\r\n\r\nstarting...\r\nconfig:\r\n  output: flixed.xml\r\n  maxConnections: 10\r\n  gzip: false\r\n  site: flixed.io\r\nloading channels...\r\n  found 94 channel(s)\r\nrun #1:\r\n  [1/94] flixed.io (en) - BravoEast.us - Dec 26, 2024 (2 programs)\r\n  [2/94] flixed.io (en) - ComedyCentralEast.us - Dec 26, 2024 (5 programs)\r\n  [3/94] flixed.io (en) - ACCNetwork.us - Dec 26, 2024 (26 programs)\r\n  [4/94] flixed.io (en) - CNN.us - Dec 26, 2024 (25 programs)\r\n  [5/94] flixed.io (en) - BloombergTV.us - Dec 26, 2024 (21 programs)\r\n  [6/94] flixed.io (en) - AEEast.us - Dec 26, 2024 (6 programs)\r\n  [7/94] flixed.io (en) - CNBC.us - Dec 26, 2024 (3 programs)\r\n  [8/94] flixed.io (en) - CinemaxEast.us - Dec 26, 2024 (14 programs)\r\n  [9/94] flixed.io (en) - AMCEast.us - Dec 26, 2024 (19 programs)\r\n  [10/94] flixed.io (en) - BigTenNetwork.us - Dec 26, 2024 (3 programs)\r\n  [11/94] flixed.io (en) - FoxWest.us - Dec 26, 2024 (8 programs)\r\n  [12/94] flixed.io (en) - FreeformEast.us - Dec 26, 2024 (2 programs)\r\n  [13/94] flixed.io (en) - FoxSports2.us - Dec 26, 2024 (2 programs)\r\n  [14/94] flixed.io (en) - FoodNetworkEast.us - Dec 26, 2024 (3 programs)\r\n...\r\n...\r\n...\r\n\r\n```\r\nSnip from xml file out\r\n![image](https://github.com/user-attachments/assets/5ed6d7eb-df59-4951-9b2c-5214e24d24ac)\r\n\r\nThe date is   September 26, 2024, 01:00:00  for Bravo\r\n\r\n',
    closed_by: null,
    reactions: {
      url: 'https://api.github.com/repos/iptv-org/epg/issues/2543/reactions',
      total_count: 0,
      '+1': 0,
      '-1': 0,
      laugh: 0,
      hooray: 0,
      confused: 0,
      heart: 0,
      rocket: 0,
      eyes: 0
    },
    timeline_url: 'https://api.github.com/repos/iptv-org/epg/issues/2543/timeline',
    performed_via_github_app: null,
    state_reason: null
  },
  {
    url: 'https://api.github.com/repos/iptv-org/epg/issues/2516',
    repository_url: 'https://api.github.com/repos/iptv-org/epg',
    labels_url: 'https://api.github.com/repos/iptv-org/epg/issues/2516/labels{/name}',
    comments_url: 'https://api.github.com/repos/iptv-org/epg/issues/2516/comments',
    events_url: 'https://api.github.com/repos/iptv-org/epg/issues/2516/events',
    html_url: 'https://github.com/iptv-org/epg/issues/2516',
    id: 2745387354,
    node_id: 'I_kwDOFLVvtM6jo0la',
    number: 2516,
    title: 'Duplicate programmes with sky.com grab',
    user: {
      login: 'misar1',
      id: 69795879,
      node_id: 'MDQ6VXNlcjY5Nzk1ODc5',
      avatar_url: 'https://avatars.githubusercontent.com/u/69795879?v=4',
      gravatar_id: '',
      url: 'https://api.github.com/users/misar1',
      html_url: 'https://github.com/misar1',
      followers_url: 'https://api.github.com/users/misar1/followers',
      following_url: 'https://api.github.com/users/misar1/following{/other_user}',
      gists_url: 'https://api.github.com/users/misar1/gists{/gist_id}',
      starred_url: 'https://api.github.com/users/misar1/starred{/owner}{/repo}',
      subscriptions_url: 'https://api.github.com/users/misar1/subscriptions',
      organizations_url: 'https://api.github.com/users/misar1/orgs',
      repos_url: 'https://api.github.com/users/misar1/repos',
      events_url: 'https://api.github.com/users/misar1/events{/privacy}',
      received_events_url: 'https://api.github.com/users/misar1/received_events',
      type: 'User',
      user_view_type: 'public',
      site_admin: false
    },
    labels: [
      {
        id: 4542348869,
        node_id: 'LA_kwDOFLVvtM8AAAABDr6-RQ',
        url: 'https://api.github.com/repos/iptv-org/epg/labels/broken%20guide',
        name: 'broken guide',
        color: 'eaeaea',
        default: false,
        description: "There's a problem with the guide"
      },
      {
        id: 7932710318,
        node_id: 'LA_kwDOFLVvtM8AAAAB2NONrg',
        url: 'https://api.github.com/repos/iptv-org/epg/labels/status:warning',
        name: 'status:warning',
        color: 'fbca06',
        default: false,
        description: 'The guide downloads, but contains errors'
      }
    ],
    state: 'open',
    locked: false,
    assignee: null,
    assignees: [],
    milestone: null,
    comments: 1,
    created_at: '2024-12-17T16:19:36Z',
    updated_at: '2024-12-27T05:27:44Z',
    closed_at: null,
    author_association: 'NONE',
    active_lock_reason: null,
    body: '### Site\n\nsky.com\n\n### Description\n\n\r\nI changed to the recently updated sky.com script a couple of days ago (using a completely new install as in the readme) and have found an anomaly. This does not occur with an identical grab using my previous installation. The grabs are for about 60 UK FTA channels which I can list if it would be helpful.\r\n\r\nA number of programmes have two identical blocks in the XML, including their start and finish times. This occurs only from around approximately 22:00 each day and up to about midnight GMT. During this period most channels are affected and it is consistent between successive grabs. In case of a timing issue I tested delays of 100, 1000, 3000 and 5000 msec but the XML was unchanged.',
    closed_by: null,
    reactions: {
      url: 'https://api.github.com/repos/iptv-org/epg/issues/2516/reactions',
      total_count: 0,
      '+1': 0,
      '-1': 0,
      laugh: 0,
      hooray: 0,
      confused: 0,
      heart: 0,
      rocket: 0,
      eyes: 0
    },
    timeline_url: 'https://api.github.com/repos/iptv-org/epg/issues/2516/timeline',
    performed_via_github_app: null,
    state_reason: null
  },
  {
    url: 'https://api.github.com/repos/iptv-org/epg/issues/2501',
    repository_url: 'https://api.github.com/repos/iptv-org/epg',
    labels_url: 'https://api.github.com/repos/iptv-org/epg/issues/2501/labels{/name}',
    comments_url: 'https://api.github.com/repos/iptv-org/epg/issues/2501/comments',
    events_url: 'https://api.github.com/repos/iptv-org/epg/issues/2501/events',
    html_url: 'https://github.com/iptv-org/epg/issues/2501',
    id: 2738899005,
    node_id: 'I_kwDOFLVvtM6jQEg9',
    number: 2501,
    title: 'Sky.com',
    user: {
      login: 'Chris230291',
      id: 5328818,
      node_id: 'MDQ6VXNlcjUzMjg4MTg=',
      avatar_url: 'https://avatars.githubusercontent.com/u/5328818?v=4',
      gravatar_id: '',
      url: 'https://api.github.com/users/Chris230291',
      html_url: 'https://github.com/Chris230291',
      followers_url: 'https://api.github.com/users/Chris230291/followers',
      following_url: 'https://api.github.com/users/Chris230291/following{/other_user}',
      gists_url: 'https://api.github.com/users/Chris230291/gists{/gist_id}',
      starred_url: 'https://api.github.com/users/Chris230291/starred{/owner}{/repo}',
      subscriptions_url: 'https://api.github.com/users/Chris230291/subscriptions',
      organizations_url: 'https://api.github.com/users/Chris230291/orgs',
      repos_url: 'https://api.github.com/users/Chris230291/repos',
      events_url: 'https://api.github.com/users/Chris230291/events{/privacy}',
      received_events_url: 'https://api.github.com/users/Chris230291/received_events',
      type: 'User',
      user_view_type: 'public',
      site_admin: false
    },
    labels: [
      {
        id: 4542348869,
        node_id: 'LA_kwDOFLVvtM8AAAABDr6-RQ',
        url: 'https://api.github.com/repos/iptv-org/epg/labels/broken%20guide',
        name: 'broken guide',
        color: 'eaeaea',
        default: false,
        description: "There's a problem with the guide"
      },
      {
        id: 7932710318,
        node_id: 'LA_kwDOFLVvtM8AAAAB2NONrg',
        url: 'https://api.github.com/repos/iptv-org/epg/labels/status:warning',
        name: 'status:warning',
        color: 'fbca06',
        default: false,
        description: 'The guide downloads, but contains errors'
      }
    ],
    state: 'open',
    locked: false,
    assignee: null,
    assignees: [],
    milestone: null,
    comments: 2,
    created_at: '2024-12-13T17:45:02Z',
    updated_at: '2024-12-27T05:25:49Z',
    closed_at: null,
    author_association: 'NONE',
    active_lock_reason: null,
    body: '### Site\n\nsky.com\n\n### Description\n\n```\r\n  <channel site="sky.com" lang="en" xmltv_id="ViaplaySports1.uk" site_id="1289">Viaplay 1 HD</channel>\r\n  <channel site="sky.com" lang="en" xmltv_id="ViaplaySports2.uk" site_id="1290">Viaplay 2 HD</channel>\r\n```\r\n\r\nThese should be "Premier Sports 1 HD" and  "Premier Sports 2 HD".\r\nAlso, the UK and ROI have different schedules for these 2 channels.',
    closed_by: null,
    reactions: {
      url: 'https://api.github.com/repos/iptv-org/epg/issues/2501/reactions',
      total_count: 0,
      '+1': 0,
      '-1': 0,
      laugh: 0,
      hooray: 0,
      confused: 0,
      heart: 0,
      rocket: 0,
      eyes: 0
    },
    timeline_url: 'https://api.github.com/repos/iptv-org/epg/issues/2501/timeline',
    performed_via_github_app: null,
    state_reason: null
  },
  {
    url: 'https://api.github.com/repos/iptv-org/epg/issues/2446',
    repository_url: 'https://api.github.com/repos/iptv-org/epg',
    labels_url: 'https://api.github.com/repos/iptv-org/epg/issues/2446/labels{/name}',
    comments_url: 'https://api.github.com/repos/iptv-org/epg/issues/2446/comments',
    events_url: 'https://api.github.com/repos/iptv-org/epg/issues/2446/events',
    html_url: 'https://github.com/iptv-org/epg/issues/2446',
    id: 2568624116,
    node_id: 'I_kwDOFLVvtM6ZGhf0',
    number: 2446,
    title: 'Eleven channels returning 0 programs on meo.pt',
    user: {
      login: 'jonatasgz',
      id: 78122211,
      node_id: 'MDQ6VXNlcjc4MTIyMjEx',
      avatar_url: 'https://avatars.githubusercontent.com/u/78122211?v=4',
      gravatar_id: '',
      url: 'https://api.github.com/users/jonatasgz',
      html_url: 'https://github.com/jonatasgz',
      followers_url: 'https://api.github.com/users/jonatasgz/followers',
      following_url: 'https://api.github.com/users/jonatasgz/following{/other_user}',
      gists_url: 'https://api.github.com/users/jonatasgz/gists{/gist_id}',
      starred_url: 'https://api.github.com/users/jonatasgz/starred{/owner}{/repo}',
      subscriptions_url: 'https://api.github.com/users/jonatasgz/subscriptions',
      organizations_url: 'https://api.github.com/users/jonatasgz/orgs',
      repos_url: 'https://api.github.com/users/jonatasgz/repos',
      events_url: 'https://api.github.com/users/jonatasgz/events{/privacy}',
      received_events_url: 'https://api.github.com/users/jonatasgz/received_events',
      type: 'User',
      user_view_type: 'public',
      site_admin: false
    },
    labels: [
      {
        id: 4542348869,
        node_id: 'LA_kwDOFLVvtM8AAAABDr6-RQ',
        url: 'https://api.github.com/repos/iptv-org/epg/labels/broken%20guide',
        name: 'broken guide',
        color: 'eaeaea',
        default: false,
        description: "There's a problem with the guide"
      },
      {
        id: 7932710318,
        node_id: 'LA_kwDOFLVvtM8AAAAB2NONrg',
        url: 'https://api.github.com/repos/iptv-org/epg/labels/status:warning',
        name: 'status:warning',
        color: 'fbca06',
        default: false,
        description: 'The guide downloads, but contains errors'
      }
    ],
    state: 'open',
    locked: false,
    assignee: null,
    assignees: [],
    milestone: null,
    comments: 2,
    created_at: '2024-10-06T12:00:48Z',
    updated_at: '2024-12-27T05:23:16Z',
    closed_at: null,
    author_association: 'NONE',
    active_lock_reason: null,
    body: '### Site\n\nmeo.pt\n\n### Description\n\nEleven (DAZN) channels return 0 programs.',
    closed_by: null,
    reactions: {
      url: 'https://api.github.com/repos/iptv-org/epg/issues/2446/reactions',
      total_count: 0,
      '+1': 0,
      '-1': 0,
      laugh: 0,
      hooray: 0,
      confused: 0,
      heart: 0,
      rocket: 0,
      eyes: 0
    },
    timeline_url: 'https://api.github.com/repos/iptv-org/epg/issues/2446/timeline',
    performed_via_github_app: null,
    state_reason: null
  },
  {
    url: 'https://api.github.com/repos/iptv-org/epg/issues/2400',
    repository_url: 'https://api.github.com/repos/iptv-org/epg',
    labels_url: 'https://api.github.com/repos/iptv-org/epg/issues/2400/labels{/name}',
    comments_url: 'https://api.github.com/repos/iptv-org/epg/issues/2400/comments',
    events_url: 'https://api.github.com/repos/iptv-org/epg/issues/2400/events',
    html_url: 'https://github.com/iptv-org/epg/issues/2400',
    id: 2370209498,
    node_id: 'I_kwDOFLVvtM6NRoba',
    number: 2400,
    title: 'tvgids.nl',
    user: {
      login: 'freearhey',
      id: 7253922,
      node_id: 'MDQ6VXNlcjcyNTM5MjI=',
      avatar_url: 'https://avatars.githubusercontent.com/u/7253922?v=4',
      gravatar_id: '',
      url: 'https://api.github.com/users/freearhey',
      html_url: 'https://github.com/freearhey',
      followers_url: 'https://api.github.com/users/freearhey/followers',
      following_url: 'https://api.github.com/users/freearhey/following{/other_user}',
      gists_url: 'https://api.github.com/users/freearhey/gists{/gist_id}',
      starred_url: 'https://api.github.com/users/freearhey/starred{/owner}{/repo}',
      subscriptions_url: 'https://api.github.com/users/freearhey/subscriptions',
      organizations_url: 'https://api.github.com/users/freearhey/orgs',
      repos_url: 'https://api.github.com/users/freearhey/repos',
      events_url: 'https://api.github.com/users/freearhey/events{/privacy}',
      received_events_url: 'https://api.github.com/users/freearhey/received_events',
      type: 'User',
      user_view_type: 'public',
      site_admin: false
    },
    labels: [
      {
        id: 4542348869,
        node_id: 'LA_kwDOFLVvtM8AAAABDr6-RQ',
        url: 'https://api.github.com/repos/iptv-org/epg/labels/broken%20guide',
        name: 'broken guide',
        color: 'eaeaea',
        default: false,
        description: "There's a problem with the guide"
      },
      {
        id: 7932710318,
        node_id: 'LA_kwDOFLVvtM8AAAAB2NONrg',
        url: 'https://api.github.com/repos/iptv-org/epg/labels/status:warning',
        name: 'status:warning',
        color: 'fbca06',
        default: false,
        description: 'The guide downloads, but contains errors'
      }
    ],
    state: 'open',
    locked: false,
    assignee: null,
    assignees: [],
    milestone: null,
    comments: 0,
    created_at: '2024-06-24T13:05:05Z',
    updated_at: '2024-12-27T05:19:25Z',
    closed_at: null,
    author_association: 'COLLABORATOR',
    active_lock_reason: null,
    body: "### Site\n\ntvgids.nl\n\n### Description\n\nTest failed:\r\n\r\n```sh\r\nnpm test -- tvgids.nl            \r\n\r\n> test\r\n> run-script-os tvgids.nl\r\n\r\n\r\n> test:default\r\n> TZ=Pacific/Nauru npx jest --runInBand tvgids.nl\r\n\r\n FAIL  sites/tvgids.nl/tvgids.nl.test.js\r\n  ✓ can generate valid url (29 ms)\r\n  ✕ can generate valid url for today (4 ms)\r\n  ✓ can parse response (307 ms)\r\n  ✓ can handle empty guide (3 ms)\r\n\r\n  ● can generate valid url for today\r\n\r\n    expect(received).toBe(expected) // Object.is equality\r\n\r\n    Expected: \"https://www.tvgids.nl/gids/npo1\"\r\n    Received: \"https://www.tvgids.nl/gids/25-06-2024/npo1\"\r\n\r\n      21 |   const today = dayjs().startOf('d')\r\n      22 |\r\n    > 23 |   expect(url({ date: today, channel })).toBe('https://www.tvgids.nl/gids/npo1')\r\n         |                                         ^\r\n      24 | })\r\n      25 |\r\n      26 | it('can parse response', () => {\r\n\r\n      at Object.<anonymous> (sites/tvgids.nl/tvgids.nl.test.js:23:41)\r\n\r\nTest Suites: 1 failed, 1 total\r\nTests:       1 failed, 3 passed, 4 total\r\nSnapshots:   0 total\r\nTime:        3.52 s\r\nRan all test suites matching /tvgids.nl/i.\r\n```",
    closed_by: null,
    reactions: {
      url: 'https://api.github.com/repos/iptv-org/epg/issues/2400/reactions',
      total_count: 0,
      '+1': 0,
      '-1': 0,
      laugh: 0,
      hooray: 0,
      confused: 0,
      heart: 0,
      rocket: 0,
      eyes: 0
    },
    timeline_url: 'https://api.github.com/repos/iptv-org/epg/issues/2400/timeline',
    performed_via_github_app: null,
    state_reason: null
  },
  {
    url: 'https://api.github.com/repos/iptv-org/epg/issues/2399',
    repository_url: 'https://api.github.com/repos/iptv-org/epg',
    labels_url: 'https://api.github.com/repos/iptv-org/epg/issues/2399/labels{/name}',
    comments_url: 'https://api.github.com/repos/iptv-org/epg/issues/2399/comments',
    events_url: 'https://api.github.com/repos/iptv-org/epg/issues/2399/events',
    html_url: 'https://github.com/iptv-org/epg/issues/2399',
    id: 2370207356,
    node_id: 'I_kwDOFLVvtM6NRn58',
    number: 2399,
    title: 'tvprofil.com',
    user: {
      login: 'freearhey',
      id: 7253922,
      node_id: 'MDQ6VXNlcjcyNTM5MjI=',
      avatar_url: 'https://avatars.githubusercontent.com/u/7253922?v=4',
      gravatar_id: '',
      url: 'https://api.github.com/users/freearhey',
      html_url: 'https://github.com/freearhey',
      followers_url: 'https://api.github.com/users/freearhey/followers',
      following_url: 'https://api.github.com/users/freearhey/following{/other_user}',
      gists_url: 'https://api.github.com/users/freearhey/gists{/gist_id}',
      starred_url: 'https://api.github.com/users/freearhey/starred{/owner}{/repo}',
      subscriptions_url: 'https://api.github.com/users/freearhey/subscriptions',
      organizations_url: 'https://api.github.com/users/freearhey/orgs',
      repos_url: 'https://api.github.com/users/freearhey/repos',
      events_url: 'https://api.github.com/users/freearhey/events{/privacy}',
      received_events_url: 'https://api.github.com/users/freearhey/received_events',
      type: 'User',
      user_view_type: 'public',
      site_admin: false
    },
    labels: [
      {
        id: 4542348869,
        node_id: 'LA_kwDOFLVvtM8AAAABDr6-RQ',
        url: 'https://api.github.com/repos/iptv-org/epg/labels/broken%20guide',
        name: 'broken guide',
        color: 'eaeaea',
        default: false,
        description: "There's a problem with the guide"
      },
      {
        id: 7932710318,
        node_id: 'LA_kwDOFLVvtM8AAAAB2NONrg',
        url: 'https://api.github.com/repos/iptv-org/epg/labels/status:warning',
        name: 'status:warning',
        color: 'fbca06',
        default: false,
        description: 'The guide downloads, but contains errors'
      }
    ],
    state: 'open',
    locked: false,
    assignee: null,
    assignees: [],
    milestone: null,
    comments: 1,
    created_at: '2024-06-24T13:04:08Z',
    updated_at: '2024-12-27T05:18:50Z',
    closed_at: null,
    author_association: 'COLLABORATOR',
    active_lock_reason: null,
    body: '### Site\n\ntvprofil.com\n\n### Description\n\nTest failed:\r\n\r\n```sh\r\nnpm test -- tvprofil.com\r\n\r\n> test\r\n> run-script-os tvprofil.com\r\n\r\n\r\n> test:default\r\n> TZ=Pacific/Nauru npx jest --runInBand tvprofil.com\r\n\r\n FAIL  sites/tvprofil.com/tvprofil.com.test.js\r\n  ✕ can generate valid url (14 ms)\r\n  ✓ can generate valid request headers (1 ms)\r\n  ✓ can parse response (76 ms)\r\n  ✓ can handle empty guide (2 ms)\r\n\r\n  ● can generate valid url\r\n\r\n    expect(received).toBe(expected) // Object.is equality\r\n\r\n    Expected: "https://tvprofil.com/bg/tv-programa/program/?datum=2023-01-12&kanal=24kitchen-bg&callback=cb&b51=818933"\r\n    Received: "https://tvprofil.com/bg/tv-programa/program/?datum=2023-01-12&kanal=24kitchen-bg&callback=cb&b49=819461"\r\n\r\n      15 |\r\n      16 | it(\'can generate valid url\', () => {\r\n    > 17 |   expect(url({ channel, date })).toBe(\r\n         |                                  ^\r\n      18 |     \'https://tvprofil.com/bg/tv-programa/program/?datum=2023-01-12&kanal=24kitchen-bg&callback=cb&b51=818933\'\r\n      19 |   )\r\n      20 | })\r\n\r\n      at Object.<anonymous> (sites/tvprofil.com/tvprofil.com.test.js:17:34)\r\n\r\nTest Suites: 1 failed, 1 total\r\nTests:       1 failed, 3 passed, 4 total\r\nSnapshots:   0 total\r\nTime:        3.307 s\r\nRan all test suites matching /tvprofil.com/i.\r\n```',
    closed_by: null,
    reactions: {
      url: 'https://api.github.com/repos/iptv-org/epg/issues/2399/reactions',
      total_count: 0,
      '+1': 0,
      '-1': 0,
      laugh: 0,
      hooray: 0,
      confused: 0,
      heart: 0,
      rocket: 0,
      eyes: 0
    },
    timeline_url: 'https://api.github.com/repos/iptv-org/epg/issues/2399/timeline',
    performed_via_github_app: null,
    state_reason: null
  },
  {
    url: 'https://api.github.com/repos/iptv-org/epg/issues/2396',
    repository_url: 'https://api.github.com/repos/iptv-org/epg',
    labels_url: 'https://api.github.com/repos/iptv-org/epg/issues/2396/labels{/name}',
    comments_url: 'https://api.github.com/repos/iptv-org/epg/issues/2396/comments',
    events_url: 'https://api.github.com/repos/iptv-org/epg/issues/2396/events',
    html_url: 'https://github.com/iptv-org/epg/issues/2396',
    id: 2370189473,
    node_id: 'I_kwDOFLVvtM6NRjih',
    number: 2396,
    title: 'iltalehti.fi',
    user: {
      login: 'freearhey',
      id: 7253922,
      node_id: 'MDQ6VXNlcjcyNTM5MjI=',
      avatar_url: 'https://avatars.githubusercontent.com/u/7253922?v=4',
      gravatar_id: '',
      url: 'https://api.github.com/users/freearhey',
      html_url: 'https://github.com/freearhey',
      followers_url: 'https://api.github.com/users/freearhey/followers',
      following_url: 'https://api.github.com/users/freearhey/following{/other_user}',
      gists_url: 'https://api.github.com/users/freearhey/gists{/gist_id}',
      starred_url: 'https://api.github.com/users/freearhey/starred{/owner}{/repo}',
      subscriptions_url: 'https://api.github.com/users/freearhey/subscriptions',
      organizations_url: 'https://api.github.com/users/freearhey/orgs',
      repos_url: 'https://api.github.com/users/freearhey/repos',
      events_url: 'https://api.github.com/users/freearhey/events{/privacy}',
      received_events_url: 'https://api.github.com/users/freearhey/received_events',
      type: 'User',
      user_view_type: 'public',
      site_admin: false
    },
    labels: [
      {
        id: 4542348869,
        node_id: 'LA_kwDOFLVvtM8AAAABDr6-RQ',
        url: 'https://api.github.com/repos/iptv-org/epg/labels/broken%20guide',
        name: 'broken guide',
        color: 'eaeaea',
        default: false,
        description: "There's a problem with the guide"
      },
      {
        id: 7932710318,
        node_id: 'LA_kwDOFLVvtM8AAAAB2NONrg',
        url: 'https://api.github.com/repos/iptv-org/epg/labels/status:warning',
        name: 'status:warning',
        color: 'fbca06',
        default: false,
        description: 'The guide downloads, but contains errors'
      }
    ],
    state: 'open',
    locked: false,
    assignee: null,
    assignees: [],
    milestone: null,
    comments: 0,
    created_at: '2024-06-24T12:56:45Z',
    updated_at: '2024-12-27T05:18:16Z',
    closed_at: null,
    author_association: 'COLLABORATOR',
    active_lock_reason: null,
    body: '### Site\n\niltalehti.fi\n\n### Description\n\nTest failed:\r\n\r\n```sh\r\nnpm test -- iltalehti.fi        \r\n\r\n> test\r\n> run-script-os iltalehti.fi\r\n\r\n\r\n> test:default\r\n> TZ=Pacific/Nauru npx jest --runInBand iltalehti.fi\r\n\r\n FAIL  sites/iltalehti.fi/iltalehti.fi.test.js\r\n  ✕ can generate valid url (10 ms)\r\n  ✓ can parse response (28 ms)\r\n  ✓ can handle empty guide (1 ms)\r\n\r\n  ● can generate valid url\r\n\r\n    expect(received).toBe(expected) // Object.is equality\r\n\r\n    Expected: "https://telkku.com/api/channel-groups/default_builtin_channelgroup1/offering?startTime=00%3A00%3A00.000&duration=PT24H&inclusionPolicy=IncludeOngoingAlso&limit=1000&tvDate=2022-10-29&view=PublicationDetails"\r\n    Received: "https://telkku.com/api/channel-groups/default_builtin_channelgroupdefault_builtin_channelgroup1/offering?startTime=00%3A00%3A00.000&duration=PT24H&inclusionPolicy=IncludeOngoingAlso&limit=1000&tvDate=2022-10-29&view=PublicationDetails"\r\n\r\n      15 |\r\n      16 | it(\'can generate valid url\', () => {\r\n    > 17 |   expect(url({ channel, date })).toBe(\r\n         |                                  ^\r\n      18 |     \'https://telkku.com/api/channel-groups/default_builtin_channelgroup1/offering?startTime=00%3A00%3A00.000&duration=PT24H&inclusionPolicy=IncludeOngoingAlso&limit=1000&tvDate=2022-10-29&view=PublicationDetails\'\r\n      19 |   )\r\n      20 | })\r\n\r\n      at Object.<anonymous> (sites/iltalehti.fi/iltalehti.fi.test.js:17:34)\r\n\r\nTest Suites: 1 failed, 1 total\r\nTests:       1 failed, 2 passed, 3 total\r\nSnapshots:   0 total\r\nTime:        3.193 s\r\nRan all test suites matching /iltalehti.fi/i.\r\n```',
    closed_by: null,
    reactions: {
      url: 'https://api.github.com/repos/iptv-org/epg/issues/2396/reactions',
      total_count: 0,
      '+1': 0,
      '-1': 0,
      laugh: 0,
      hooray: 0,
      confused: 0,
      heart: 0,
      rocket: 0,
      eyes: 0
    },
    timeline_url: 'https://api.github.com/repos/iptv-org/epg/issues/2396/timeline',
    performed_via_github_app: null,
    state_reason: null
  },
  {
    url: 'https://api.github.com/repos/iptv-org/epg/issues/2395',
    repository_url: 'https://api.github.com/repos/iptv-org/epg',
    labels_url: 'https://api.github.com/repos/iptv-org/epg/issues/2395/labels{/name}',
    comments_url: 'https://api.github.com/repos/iptv-org/epg/issues/2395/comments',
    events_url: 'https://api.github.com/repos/iptv-org/epg/issues/2395/events',
    html_url: 'https://github.com/iptv-org/epg/issues/2395',
    id: 2370186157,
    node_id: 'I_kwDOFLVvtM6NRiut',
    number: 2395,
    title: 'chaines-tv.orange.fr',
    user: {
      login: 'freearhey',
      id: 7253922,
      node_id: 'MDQ6VXNlcjcyNTM5MjI=',
      avatar_url: 'https://avatars.githubusercontent.com/u/7253922?v=4',
      gravatar_id: '',
      url: 'https://api.github.com/users/freearhey',
      html_url: 'https://github.com/freearhey',
      followers_url: 'https://api.github.com/users/freearhey/followers',
      following_url: 'https://api.github.com/users/freearhey/following{/other_user}',
      gists_url: 'https://api.github.com/users/freearhey/gists{/gist_id}',
      starred_url: 'https://api.github.com/users/freearhey/starred{/owner}{/repo}',
      subscriptions_url: 'https://api.github.com/users/freearhey/subscriptions',
      organizations_url: 'https://api.github.com/users/freearhey/orgs',
      repos_url: 'https://api.github.com/users/freearhey/repos',
      events_url: 'https://api.github.com/users/freearhey/events{/privacy}',
      received_events_url: 'https://api.github.com/users/freearhey/received_events',
      type: 'User',
      user_view_type: 'public',
      site_admin: false
    },
    labels: [
      {
        id: 4542348869,
        node_id: 'LA_kwDOFLVvtM8AAAABDr6-RQ',
        url: 'https://api.github.com/repos/iptv-org/epg/labels/broken%20guide',
        name: 'broken guide',
        color: 'eaeaea',
        default: false,
        description: "There's a problem with the guide"
      },
      {
        id: 7932710318,
        node_id: 'LA_kwDOFLVvtM8AAAAB2NONrg',
        url: 'https://api.github.com/repos/iptv-org/epg/labels/status:warning',
        name: 'status:warning',
        color: 'fbca06',
        default: false,
        description: 'The guide downloads, but contains errors'
      }
    ],
    state: 'open',
    locked: false,
    assignee: null,
    assignees: [],
    milestone: null,
    comments: 2,
    created_at: '2024-06-24T12:55:21Z',
    updated_at: '2024-12-27T05:17:25Z',
    closed_at: null,
    author_association: 'COLLABORATOR',
    active_lock_reason: null,
    body: '### Site\r\n\r\nchaines-tv.orange.fr\r\n\r\n### Description\r\n\r\nTest failed:\r\n\r\n```sh\r\nnpm test -- chaines-tv.orange.fr\r\n\r\n> test\r\n> run-script-os chaines-tv.orange.fr\r\n\r\n\r\n> test:default\r\n> TZ=Pacific/Nauru npx jest --runInBand chaines-tv.orange.fr\r\n\r\n FAIL  sites/chaines-tv.orange.fr/chaines-tv.orange.fr.test.js\r\n  ✓ can generate valid url (5 ms)\r\n  ✕ can parse response (12 ms)\r\n  ✓ can handle empty guide (1 ms)\r\n\r\n  ● can parse response\r\n\r\n    expect(received).toMatchObject(expected)\r\n\r\n    - Expected  - 1\r\n    + Received  + 1\r\n\r\n    @@ -3,8 +3,8 @@\r\n          "category": "Série Suspense",\r\n          "description": "Un tueur en série prend un plaisir pervers à prévenir les autorités de Tallahassee avant chaque nouveau meurtre. Rossi apprend le décès d\'un de ses vieux amis.",\r\n          "icon": "https://proxymedia.woopic.com/340/p/169_EMI_9697669.jpg",\r\n          "start": "2021-11-07T23:35:00.000Z",\r\n          "stop": "2021-11-08T00:20:00.000Z",\r\n    -     "title": "Tête de liste",\r\n    +     "title": "Esprits criminels",\r\n        },\r\n      ]\r\n\r\n      23 | it(\'can parse response\', () => {\r\n      24 |   const result = parser({ date, channel, content })\r\n    > 25 |   expect(result).toMatchObject([\r\n         |                  ^\r\n      26 |     {\r\n      27 |       start: \'2021-11-07T23:35:00.000Z\',\r\n      28 |       stop: \'2021-11-08T00:20:00.000Z\',\r\n\r\n      at Object.<anonymous> (sites/chaines-tv.orange.fr/chaines-tv.orange.fr.test.js:25:18)\r\n\r\nTest Suites: 1 failed, 1 total\r\nTests:       1 failed, 2 passed, 3 total\r\nSnapshots:   0 total\r\nTime:        4.003 s\r\nRan all test suites matching /chaines-tv.orange.fr/i.\r\n```',
    closed_by: null,
    reactions: {
      url: 'https://api.github.com/repos/iptv-org/epg/issues/2395/reactions',
      total_count: 0,
      '+1': 0,
      '-1': 0,
      laugh: 0,
      hooray: 0,
      confused: 0,
      heart: 0,
      rocket: 0,
      eyes: 0
    },
    timeline_url: 'https://api.github.com/repos/iptv-org/epg/issues/2395/timeline',
    performed_via_github_app: null,
    state_reason: null
  },
  {
    url: 'https://api.github.com/repos/iptv-org/epg/issues/2304',
    repository_url: 'https://api.github.com/repos/iptv-org/epg',
    labels_url: 'https://api.github.com/repos/iptv-org/epg/issues/2304/labels{/name}',
    comments_url: 'https://api.github.com/repos/iptv-org/epg/issues/2304/comments',
    events_url: 'https://api.github.com/repos/iptv-org/epg/issues/2304/events',
    html_url: 'https://github.com/iptv-org/epg/issues/2304',
    id: 2064638324,
    node_id: 'I_kwDOFLVvtM57D-F0',
    number: 2304,
    title: 'digiturk.com.tr Missing Channel Identifications',
    user: {
      login: 'UzunMuhalefet',
      id: 80906858,
      node_id: 'MDQ6VXNlcjgwOTA2ODU4',
      avatar_url: 'https://avatars.githubusercontent.com/u/80906858?v=4',
      gravatar_id: '',
      url: 'https://api.github.com/users/UzunMuhalefet',
      html_url: 'https://github.com/UzunMuhalefet',
      followers_url: 'https://api.github.com/users/UzunMuhalefet/followers',
      following_url: 'https://api.github.com/users/UzunMuhalefet/following{/other_user}',
      gists_url: 'https://api.github.com/users/UzunMuhalefet/gists{/gist_id}',
      starred_url: 'https://api.github.com/users/UzunMuhalefet/starred{/owner}{/repo}',
      subscriptions_url: 'https://api.github.com/users/UzunMuhalefet/subscriptions',
      organizations_url: 'https://api.github.com/users/UzunMuhalefet/orgs',
      repos_url: 'https://api.github.com/users/UzunMuhalefet/repos',
      events_url: 'https://api.github.com/users/UzunMuhalefet/events{/privacy}',
      received_events_url: 'https://api.github.com/users/UzunMuhalefet/received_events',
      type: 'User',
      user_view_type: 'public',
      site_admin: false
    },
    labels: [
      {
        id: 4542348869,
        node_id: 'LA_kwDOFLVvtM8AAAABDr6-RQ',
        url: 'https://api.github.com/repos/iptv-org/epg/labels/broken%20guide',
        name: 'broken guide',
        color: 'eaeaea',
        default: false,
        description: "There's a problem with the guide"
      },
      {
        id: 7932710318,
        node_id: 'LA_kwDOFLVvtM8AAAAB2NONrg',
        url: 'https://api.github.com/repos/iptv-org/epg/labels/status:warning',
        name: 'status:warning',
        color: 'fbca06',
        default: false,
        description: 'The guide downloads, but contains errors'
      }
    ],
    state: 'open',
    locked: false,
    assignee: null,
    assignees: [],
    milestone: null,
    comments: 0,
    created_at: '2024-01-03T20:57:58Z',
    updated_at: '2024-12-27T05:32:37Z',
    closed_at: null,
    author_association: 'NONE',
    active_lock_reason: null,
    body: '### Site\r\n\r\ndigiturk.com.tr\r\n\r\n### Describe your issue\r\n\r\nThe following channels can be corrected as follows. (I added the TVG-IDs if they exist in https://iptv-org.github.io/)\r\n\r\n```\r\n<channel site="digiturk.com.tr" lang="tr" xmltv_id="24TV.tr" site_id="40">KANAL 24 HD</channel>\r\n<channel site="digiturk.com.tr" lang="tr" xmltv_id="TarihTV.tr" site_id="184">TARIH TV HD</channel>\r\n<channel site="digiturk.com.tr" lang="tr" xmltv_id="SozcuTV.tr" site_id="60">SÖZCÜ TV HD</channel>\r\n```\r\n\r\nLet me clarify the cases:\r\n- SZC changed its name to Sözcü TV\r\n- 24 TV often called as Kanal (Channel) 24\r\n- Tarih TV is straightforward.\r\n',
    closed_by: null,
    reactions: {
      url: 'https://api.github.com/repos/iptv-org/epg/issues/2304/reactions',
      total_count: 0,
      '+1': 0,
      '-1': 0,
      laugh: 0,
      hooray: 0,
      confused: 0,
      heart: 0,
      rocket: 0,
      eyes: 0
    },
    timeline_url: 'https://api.github.com/repos/iptv-org/epg/issues/2304/timeline',
    performed_via_github_app: null,
    state_reason: null
  },
  {
    url: 'https://api.github.com/repos/iptv-org/epg/issues/2303',
    repository_url: 'https://api.github.com/repos/iptv-org/epg',
    labels_url: 'https://api.github.com/repos/iptv-org/epg/issues/2303/labels{/name}',
    comments_url: 'https://api.github.com/repos/iptv-org/epg/issues/2303/comments',
    events_url: 'https://api.github.com/repos/iptv-org/epg/issues/2303/events',
    html_url: 'https://github.com/iptv-org/epg/issues/2303',
    id: 2064633657,
    node_id: 'I_kwDOFLVvtM57D885',
    number: 2303,
    title: 'dsmart.com.tr Channel Identifications',
    user: {
      login: 'UzunMuhalefet',
      id: 80906858,
      node_id: 'MDQ6VXNlcjgwOTA2ODU4',
      avatar_url: 'https://avatars.githubusercontent.com/u/80906858?v=4',
      gravatar_id: '',
      url: 'https://api.github.com/users/UzunMuhalefet',
      html_url: 'https://github.com/UzunMuhalefet',
      followers_url: 'https://api.github.com/users/UzunMuhalefet/followers',
      following_url: 'https://api.github.com/users/UzunMuhalefet/following{/other_user}',
      gists_url: 'https://api.github.com/users/UzunMuhalefet/gists{/gist_id}',
      starred_url: 'https://api.github.com/users/UzunMuhalefet/starred{/owner}{/repo}',
      subscriptions_url: 'https://api.github.com/users/UzunMuhalefet/subscriptions',
      organizations_url: 'https://api.github.com/users/UzunMuhalefet/orgs',
      repos_url: 'https://api.github.com/users/UzunMuhalefet/repos',
      events_url: 'https://api.github.com/users/UzunMuhalefet/events{/privacy}',
      received_events_url: 'https://api.github.com/users/UzunMuhalefet/received_events',
      type: 'User',
      user_view_type: 'public',
      site_admin: false
    },
    labels: [
      {
        id: 4542348869,
        node_id: 'LA_kwDOFLVvtM8AAAABDr6-RQ',
        url: 'https://api.github.com/repos/iptv-org/epg/labels/broken%20guide',
        name: 'broken guide',
        color: 'eaeaea',
        default: false,
        description: "There's a problem with the guide"
      },
      {
        id: 7932710318,
        node_id: 'LA_kwDOFLVvtM8AAAAB2NONrg',
        url: 'https://api.github.com/repos/iptv-org/epg/labels/status:warning',
        name: 'status:warning',
        color: 'fbca06',
        default: false,
        description: 'The guide downloads, but contains errors'
      }
    ],
    state: 'open',
    locked: false,
    assignee: null,
    assignees: [],
    milestone: null,
    comments: 1,
    created_at: '2024-01-03T20:53:34Z',
    updated_at: '2024-12-27T05:44:16Z',
    closed_at: null,
    author_association: 'NONE',
    active_lock_reason: null,
    body: '### Describe your issue\r\n\r\nThe following channels can be corrected as follows. (I added the TVG-IDs if they exist in https://iptv-org.github.io/)\r\n\r\n```\r\n<channel site="dsmart.com.tr" lang="tr" xmltv_id="Number1TV.tr" site_id="102#58d29bb0eefad3db9c60623c">NR1</channel>\r\n<channel site="dsmart.com.tr" lang="tr" xmltv_id="Number1Turk.tr" site_id="104#58d29bb0eefad3db9c606245">NR1 Türk</channel>\r\n<channel site="dsmart.com.tr" lang="tr" xmltv_id="EBATVIlkokul.tr" site_id="123#5e75c6f5cfef0b15938bc9b9">TRT EBA TV İlkokul</channel>\r\n<channel site="dsmart.com.tr" lang="tr" xmltv_id="EBATVOrtaokul.tr" site_id="124#5e75c923cfef0b15938bc9cc">TRT EBA TV Ortaokul</channel>\r\n<channel site="dsmart.com.tr" lang="tr" xmltv_id="EBATVLise.tr" site_id="125#5e75c9d1cfef0b15938bc9d1">TRT EBA TV Lise</channel>\r\n<channel site="dsmart.com.tr" lang="tr" xmltv_id="CiftciTV.tr" site_id="139#59dcaaaccfef0b4d80a47d7e">Çifçi TV</channel>\r\n<channel site="dsmart.com.tr" lang="tr" xmltv_id="On6.tr" site_id="150#59dcbc42cfef0b4d80a49628">Kanal 16</channel>\r\n<channel site="dsmart.com.tr" lang="tr" xmltv_id="FlashTV.tr" site_id="163#6163ee3dcfef0b1593d572b0">Flash Haber</channel>\r\n<channel site="dsmart.com.tr" lang="tr" xmltv_id="KocaeliTV.tr" site_id="168#59dcbe7dcfef0b4d80a4964c">Yeni Kocaeli TV</channel>\r\n<channel site="dsmart.com.tr" lang="tr" xmltv_id="ATV.tr" site_id="198#58d29bb0eefad3db9c606247">ATV Turkiye SD</channel>\r\n<channel site="dsmart.com.tr" lang="tr" xmltv_id="EBATVIlkokul" site_id="207#5e7865eacfef0b15938c1bb0">TRT EBA TV İlkokul SD</channel>\r\n<channel site="dsmart.com.tr" lang="tr" xmltv_id="EBATVOrtaokul" site_id="208#5e78662ecfef0b15938c1c03">TRT EBA TV Ortaokul SD</channel>\r\n<channel site="dsmart.com.tr" lang="tr" xmltv_id="EBATVLise" site_id="209#5e7866dfcfef0b15938c1c1b">TRT EBA TV Lise SD</channel>\r\n<channel site="dsmart.com.tr" lang="tr" xmltv_id="TarihTV.tr" site_id="63#64edfc67cfef0b02d2c038c5">Tarih Tv</channel>\r\n<channel site="dsmart.com.tr" lang="tr" xmltv_id="SozcuTV.tr" site_id="87#63ecd91acfef0b02d2687aed">SZC</channel>\r\n<channel site="dsmart.com.tr" lang="tr" xmltv_id="TRT3.tr" site_id="93#58d29bb0eefad3db9c606231">TRT 3 Spor</channel>\r\n``` \r\n\r\nLet me clarify the cases: \r\n\r\n- NR1 stands for Number One\r\n- Cifci TV - Çiftçi TV - misspelling\r\n- The number 16 is spelled as onaltı (on -> 10, altı->6, on6 -> 16) in Turkish so on6 - Kanal 16\r\n- Flash TV changed its name to Flash Haber TV\r\n- SZC changed its name to Sözcü TV\r\n- TRT 3 is a strange channel that usually streams the same content as TRT Spor but when there is a Turkish parliament event it switches to that event. So, the channel is both called TRT 3 and TRT 3 Spor.\r\n',
    closed_by: null,
    reactions: {
      url: 'https://api.github.com/repos/iptv-org/epg/issues/2303/reactions',
      total_count: 0,
      '+1': 0,
      '-1': 0,
      laugh: 0,
      hooray: 0,
      confused: 0,
      heart: 0,
      rocket: 0,
      eyes: 0
    },
    timeline_url: 'https://api.github.com/repos/iptv-org/epg/issues/2303/timeline',
    performed_via_github_app: null,
    state_reason: null
  },
  {
    url: 'https://api.github.com/repos/iptv-org/epg/issues/2272',
    repository_url: 'https://api.github.com/repos/iptv-org/epg',
    labels_url: 'https://api.github.com/repos/iptv-org/epg/issues/2272/labels{/name}',
    comments_url: 'https://api.github.com/repos/iptv-org/epg/issues/2272/comments',
    events_url: 'https://api.github.com/repos/iptv-org/epg/issues/2272/events',
    html_url: 'https://github.com/iptv-org/epg/issues/2272',
    id: 2022135766,
    node_id: 'I_kwDOFLVvtM54h1fW',
    number: 2272,
    title: 'Film titles with numbers only in the title (as in "1900" or "1917") don\'t show up',
    user: {
      login: 'GlamoramaAttack',
      id: 116585465,
      node_id: 'U_kgDOBvLz-Q',
      avatar_url: 'https://avatars.githubusercontent.com/u/116585465?v=4',
      gravatar_id: '',
      url: 'https://api.github.com/users/GlamoramaAttack',
      html_url: 'https://github.com/GlamoramaAttack',
      followers_url: 'https://api.github.com/users/GlamoramaAttack/followers',
      following_url: 'https://api.github.com/users/GlamoramaAttack/following{/other_user}',
      gists_url: 'https://api.github.com/users/GlamoramaAttack/gists{/gist_id}',
      starred_url: 'https://api.github.com/users/GlamoramaAttack/starred{/owner}{/repo}',
      subscriptions_url: 'https://api.github.com/users/GlamoramaAttack/subscriptions',
      organizations_url: 'https://api.github.com/users/GlamoramaAttack/orgs',
      repos_url: 'https://api.github.com/users/GlamoramaAttack/repos',
      events_url: 'https://api.github.com/users/GlamoramaAttack/events{/privacy}',
      received_events_url: 'https://api.github.com/users/GlamoramaAttack/received_events',
      type: 'User',
      user_view_type: 'public',
      site_admin: false
    },
    labels: [
      {
        id: 4542348869,
        node_id: 'LA_kwDOFLVvtM8AAAABDr6-RQ',
        url: 'https://api.github.com/repos/iptv-org/epg/labels/broken%20guide',
        name: 'broken guide',
        color: 'eaeaea',
        default: false,
        description: "There's a problem with the guide"
      },
      {
        id: 7932710318,
        node_id: 'LA_kwDOFLVvtM8AAAAB2NONrg',
        url: 'https://api.github.com/repos/iptv-org/epg/labels/status:warning',
        name: 'status:warning',
        color: 'fbca06',
        default: false,
        description: 'The guide downloads, but contains errors'
      }
    ],
    state: 'open',
    locked: false,
    assignee: null,
    assignees: [],
    milestone: null,
    comments: 2,
    created_at: '2023-12-02T17:29:50Z',
    updated_at: '2024-12-27T05:02:05Z',
    closed_at: null,
    author_association: 'NONE',
    active_lock_reason: null,
    body: '### Site\r\n\r\ntvpassport.com\r\n\r\n### Describe your issue\r\n\r\nFilm titles with numbers only in the title -as in "1900" or "1917"- don\'t show up at all.\r\n\r\nSorry, I don\'t understand anything about how to write a script or fix it but I see there is notable difference in the **guide.xml** file - the examples are excerpts from tvpassport.com. This isn\'t a new bug I think, it\'s just that I thought for a long time it\'s a Kodi problem before looking into the guide.xml file...\r\n\r\n```\r\nchannel="Showtime2East.us"><title lang="en">The Caine Mutiny Court-Martial</title><desc lang="en">A \r\nchannel="Showtime2East.us"><desc lang="en">Two British soldiers receive seemingly impossible orders \r\nchannel="Showtime2East.us"><title lang="en">There Will Be Blood</title><desc lang="en">Daniel \r\n```\r\nor:\r\n\r\n```\r\nchannel="MGMPlusEast.us"><title lang="en">A Fistful of Dynamite</title><desc lang="en">A thief \r\nchannel="MGMPlusEast.us"><desc lang="en">The son (Robert De Niro) of a landowner and the son \r\nchannel="MGMPlusEast.us"><title lang="en">Indecent Proposal</title><desc lang="en">A Las Vegas \r\n```\r\n\r\nFor some reason "title lang" gets replaced by "desc lang" and the film title is nowhere displayed.\r\n\r\nOn Kodi it looks like this for the films and you can also see it\'s not a problem if the film title includes more than numbers (see "88 Minutes" or "Resistance: 1942"). But titles as "1900", "1917" or "1408" (Horror with John Cusack) appear blank.\r\n\r\n![NoTitleWithNumbers](https://github.com/iptv-org/epg/assets/116585465/155f98f8-8529-4c42-af3c-def1edcf5651)\r\n\r\nI\'m not sure whether the problem also exists with other sources than tvpassport.com because I use only two other (German language) EPG sources that have currently no film titles with numbers only. But I assume it\'s a bug if it\'s not reduced to tvpassport.',
    closed_by: null,
    reactions: {
      url: 'https://api.github.com/repos/iptv-org/epg/issues/2272/reactions',
      total_count: 0,
      '+1': 0,
      '-1': 0,
      laugh: 0,
      hooray: 0,
      confused: 0,
      heart: 0,
      rocket: 0,
      eyes: 0
    },
    timeline_url: 'https://api.github.com/repos/iptv-org/epg/issues/2272/timeline',
    performed_via_github_app: null,
    state_reason: null
  },
  {
    url: 'https://api.github.com/repos/iptv-org/epg/issues/2176',
    repository_url: 'https://api.github.com/repos/iptv-org/epg',
    labels_url: 'https://api.github.com/repos/iptv-org/epg/issues/2176/labels{/name}',
    comments_url: 'https://api.github.com/repos/iptv-org/epg/issues/2176/comments',
    events_url: 'https://api.github.com/repos/iptv-org/epg/issues/2176/events',
    html_url: 'https://github.com/iptv-org/epg/issues/2176',
    id: 1915947653,
    node_id: 'I_kwDOFLVvtM5yMwqF',
    number: 2176,
    title: 'tvtv',
    user: {
      login: 'jvdillon',
      id: 1137078,
      node_id: 'MDQ6VXNlcjExMzcwNzg=',
      avatar_url: 'https://avatars.githubusercontent.com/u/1137078?v=4',
      gravatar_id: '',
      url: 'https://api.github.com/users/jvdillon',
      html_url: 'https://github.com/jvdillon',
      followers_url: 'https://api.github.com/users/jvdillon/followers',
      following_url: 'https://api.github.com/users/jvdillon/following{/other_user}',
      gists_url: 'https://api.github.com/users/jvdillon/gists{/gist_id}',
      starred_url: 'https://api.github.com/users/jvdillon/starred{/owner}{/repo}',
      subscriptions_url: 'https://api.github.com/users/jvdillon/subscriptions',
      organizations_url: 'https://api.github.com/users/jvdillon/orgs',
      repos_url: 'https://api.github.com/users/jvdillon/repos',
      events_url: 'https://api.github.com/users/jvdillon/events{/privacy}',
      received_events_url: 'https://api.github.com/users/jvdillon/received_events',
      type: 'User',
      user_view_type: 'public',
      site_admin: false
    },
    labels: [
      {
        id: 4542348869,
        node_id: 'LA_kwDOFLVvtM8AAAABDr6-RQ',
        url: 'https://api.github.com/repos/iptv-org/epg/labels/broken%20guide',
        name: 'broken guide',
        color: 'eaeaea',
        default: false,
        description: "There's a problem with the guide"
      },
      {
        id: 7932710318,
        node_id: 'LA_kwDOFLVvtM8AAAAB2NONrg',
        url: 'https://api.github.com/repos/iptv-org/epg/labels/status:warning',
        name: 'status:warning',
        color: 'fbca06',
        default: false,
        description: 'The guide downloads, but contains errors'
      }
    ],
    state: 'open',
    locked: false,
    assignee: null,
    assignees: [],
    milestone: null,
    comments: 6,
    created_at: '2023-09-27T16:34:00Z',
    updated_at: '2024-12-27T04:55:00Z',
    closed_at: null,
    author_association: 'NONE',
    active_lock_reason: null,
    body: '### Site\r\n\r\ntvtv.us\r\n\r\n### Description\r\n\r\nStarts getting error 429 after several 100 scrapes. I tried setting the delay to 1000ms, 1500ms, and 2000ms but keep seeing the issue.\r\n\r\nIt almost appears to happen after a sequence of 0 program scrapes. I wonder if the delay is not happening when nothing is downloaded which causes tvtv.us to throttle which triggers 0 programs downloaded. (Ie a feedback loop)',
    closed_by: null,
    reactions: {
      url: 'https://api.github.com/repos/iptv-org/epg/issues/2176/reactions',
      total_count: 0,
      '+1': 0,
      '-1': 0,
      laugh: 0,
      hooray: 0,
      confused: 0,
      heart: 0,
      rocket: 0,
      eyes: 0
    },
    timeline_url: 'https://api.github.com/repos/iptv-org/epg/issues/2176/timeline',
    performed_via_github_app: null,
    state_reason: null
  }
]
