name: ⚠️ Broken Guide
description: Report an error in one of the guides
labels: ['⚠️ broken guide']

body:
  - type: markdown
    attributes:
      value: |
        Please fill out the issue template as much as you can so we could efficiently process your request.

  - type: input
    attributes:
      label: Guide
      description: Link to the broken guide
      placeholder: 'https://iptv-org.github.io/epg/guides/us.xml'
    validations:
      required: true

  - type: textarea
    attributes:
      label: Description
      description: Describe the issue in details
    validations:
      required: true