const countries = {
  al: { show: false, channels: [], filtered: [], code: 'al', name: 'Albania' },
  dz: { show: false, channels: [], filtered: [], code: 'dz', name: 'Algeria' },
  ao: { show: false, channels: [], filtered: [], code: 'ao', name: 'Angola' },
  ar: { show: false, channels: [], filtered: [], code: 'ar', name: 'Argentina' },
  am: { show: false, channels: [], filtered: [], code: 'am', name: 'Armenia' },
  au: { show: false, channels: [], filtered: [], code: 'au', name: 'Australia' },
  at: { show: false, channels: [], filtered: [], code: 'at', name: 'Austria' },
  az: { show: false, channels: [], filtered: [], code: 'az', name: 'Azerbaijan' },
  by: { show: false, channels: [], filtered: [], code: 'by', name: 'Belarus' },
  be: { show: false, channels: [], filtered: [], code: 'be', name: 'Belgium' },
  bj: { show: false, channels: [], filtered: [], code: 'bj', name: 'Benin' },
  bo: {
    show: false,
    channels: [],
    filtered: [],
    code: 'bo',
    name: 'Bolivia (Plurinational State of)'
  },
  ba: { show: false, channels: [], filtered: [], code: 'ba', name: 'Bosnia and Herzegovina' },
  br: { show: false, channels: [], filtered: [], code: 'br', name: 'Brazil' },
  bn: { show: false, channels: [], filtered: [], code: 'bn', name: 'Brunei Darussalam' },
  bg: { show: false, channels: [], filtered: [], code: 'bg', name: 'Bulgaria' },
  ca: { show: false, channels: [], filtered: [], code: 'ca', name: 'Canada' },
  cl: { show: false, channels: [], filtered: [], code: 'cl', name: 'Chile' },
  cn: { show: false, channels: [], filtered: [], code: 'cn', name: 'China' },
  co: { show: false, channels: [], filtered: [], code: 'co', name: 'Colombia' },
  cr: { show: false, channels: [], filtered: [], code: 'cr', name: 'Costa Rica' },
  hr: { show: false, channels: [], filtered: [], code: 'hr', name: 'Croatia' },
  cu: { show: false, channels: [], filtered: [], code: 'cu', name: 'Cuba' },
  cw: { show: false, channels: [], filtered: [], code: 'cw', name: 'Cura\u00e7ao' },
  cy: { show: false, channels: [], filtered: [], code: 'cy', name: 'Cyprus' },
  cz: { show: false, channels: [], filtered: [], code: 'cz', name: 'Czech Republic' },
  dk: { show: false, channels: [], filtered: [], code: 'dk', name: 'Denmark' },
  do: { show: false, channels: [], filtered: [], code: 'do', name: 'Dominican Republic' },
  ec: { show: false, channels: [], filtered: [], code: 'ec', name: 'Ecuador' },
  eg: { show: false, channels: [], filtered: [], code: 'eg', name: 'Egypt' },
  sv: { show: false, channels: [], filtered: [], code: 'sv', name: 'El Salvador' },
  ee: { show: false, channels: [], filtered: [], code: 'ee', name: 'Estonia' },
  fi: { show: false, channels: [], filtered: [], code: 'fi', name: 'Finland' },
  fr: { show: false, channels: [], filtered: [], code: 'fr', name: 'France' },
  ge: { show: false, channels: [], filtered: [], code: 'ge', name: 'Georgia' },
  de: { show: false, channels: [], filtered: [], code: 'de', name: 'Germany' },
  gr: { show: false, channels: [], filtered: [], code: 'gr', name: 'Greece' },
  gt: { show: false, channels: [], filtered: [], code: 'gt', name: 'Guatemala' },
  gn: { show: false, channels: [], filtered: [], code: 'gn', name: 'Guinea' },
  ht: { show: false, channels: [], filtered: [], code: 'ht', name: 'Haiti' },
  hn: { show: false, channels: [], filtered: [], code: 'hn', name: 'Honduras' },
  hk: { show: false, channels: [], filtered: [], code: 'hk', name: 'Hong Kong' },
  hu: { show: false, channels: [], filtered: [], code: 'hu', name: 'Hungary' },
  is: { show: false, channels: [], filtered: [], code: 'is', name: 'Iceland' },
  in: { show: false, channels: [], filtered: [], code: 'in', name: 'India' },
  id: { show: false, channels: [], filtered: [], code: 'id', name: 'Indonesia' },
  ir: { show: false, channels: [], filtered: [], code: 'ir', name: 'Iran (Islamic Republic of)' },
  iq: { show: false, channels: [], filtered: [], code: 'iq', name: 'Iraq' },
  ie: { show: false, channels: [], filtered: [], code: 'ie', name: 'Ireland' },
  il: { show: false, channels: [], filtered: [], code: 'il', name: 'Israel' },
  it: { show: false, channels: [], filtered: [], code: 'it', name: 'Italy' },
  jm: { show: false, channels: [], filtered: [], code: 'jm', name: 'Jamaica' },
  jp: { show: false, channels: [], filtered: [], code: 'jp', name: 'Japan' },
  jo: { show: false, channels: [], filtered: [], code: 'jo', name: 'Jordan' },
  kz: { show: false, channels: [], filtered: [], code: 'kz', name: 'Kazakhstan' },
  ke: { show: false, channels: [], filtered: [], code: 'ke', name: 'Kenya' },
  kr: { show: false, channels: [], filtered: [], code: 'kr', name: 'Korea (Republic of)' },
  kw: { show: false, channels: [], filtered: [], code: 'kw', name: 'Kuwait' },
  kg: { show: false, channels: [], filtered: [], code: 'kg', name: 'Kyrgyzstan' },
  lv: { show: false, channels: [], filtered: [], code: 'lv', name: 'Latvia' },
  lb: { show: false, channels: [], filtered: [], code: 'lb', name: 'Lebanon' },
  lt: { show: false, channels: [], filtered: [], code: 'lt', name: 'Lithuania' },
  lu: { show: false, channels: [], filtered: [], code: 'lu', name: 'Luxembourg' },
  mo: { show: false, channels: [], filtered: [], code: 'mo', name: 'Macao' },
  mk: {
    show: false,
    channels: [],
    filtered: [],
    code: 'mk',
    name: 'Macedonia, the former Yugoslav Republic of'
  },
  my: { show: false, channels: [], filtered: [], code: 'my', name: 'Malaysia' },
  mt: { show: false, channels: [], filtered: [], code: 'mt', name: 'Malta' },
  mu: { show: false, channels: [], filtered: [], code: 'mu', name: 'Mauritius' },
  mx: { show: false, channels: [], filtered: [], code: 'mx', name: 'Mexico' },
  md: { show: false, channels: [], filtered: [], code: 'md', name: 'Moldova (Republic of)' },
  mn: { show: false, channels: [], filtered: [], code: 'mn', name: 'Mongolia' },
  me: { show: false, channels: [], filtered: [], code: 'me', name: 'Montenegro' },
  ma: { show: false, channels: [], filtered: [], code: 'ma', name: 'Morocco' },
  mz: { show: false, channels: [], filtered: [], code: 'mz', name: 'Mozambique' },
  mm: { show: false, channels: [], filtered: [], code: 'mm', name: 'Myanmar' },
  nl: { show: false, channels: [], filtered: [], code: 'nl', name: 'Netherlands' },
  nz: { show: false, channels: [], filtered: [], code: 'nz', name: 'New Zealand' },
  ni: { show: false, channels: [], filtered: [], code: 'ni', name: 'Nicaragua' },
  ng: { show: false, channels: [], filtered: [], code: 'ng', name: 'Nigeria' },
  no: { show: false, channels: [], filtered: [], code: 'no', name: 'Norway' },
  pk: { show: false, channels: [], filtered: [], code: 'pk', name: 'Pakistan' },
  pa: { show: false, channels: [], filtered: [], code: 'pa', name: 'Panama' },
  py: { show: false, channels: [], filtered: [], code: 'py', name: 'Paraguay' },
  pe: { show: false, channels: [], filtered: [], code: 'pe', name: 'Peru' },
  ph: { show: false, channels: [], filtered: [], code: 'ph', name: 'Philippines' },
  pl: { show: false, channels: [], filtered: [], code: 'pl', name: 'Poland' },
  pt: { show: false, channels: [], filtered: [], code: 'pt', name: 'Portugal' },
  qa: { show: false, channels: [], filtered: [], code: 'qa', name: 'Qatar' },
  ro: { show: false, channels: [], filtered: [], code: 'ro', name: 'Romania' },
  ru: { show: false, channels: [], filtered: [], code: 'ru', name: 'Russian Federation' },
  sa: { show: false, channels: [], filtered: [], code: 'sa', name: 'Saudi Arabia' },
  rs: { show: false, channels: [], filtered: [], code: 'rs', name: 'Serbia' },
  sg: { show: false, channels: [], filtered: [], code: 'sg', name: 'Singapore' },
  sk: { show: false, channels: [], filtered: [], code: 'sk', name: 'Slovakia' },
  si: { show: false, channels: [], filtered: [], code: 'si', name: 'Slovenia' },
  sb: { show: false, channels: [], filtered: [], code: 'sb', name: 'Solomon Islands' },
  za: { show: false, channels: [], filtered: [], code: 'za', name: 'South Africa' },
  es: { show: false, channels: [], filtered: [], code: 'es', name: 'Spain' },
  se: { show: false, channels: [], filtered: [], code: 'se', name: 'Sweden' },
  ch: { show: false, channels: [], filtered: [], code: 'ch', name: 'Switzerland' },
  sy: { show: false, channels: [], filtered: [], code: 'sy', name: 'Syrian Arab Republic' },
  tw: { show: false, channels: [], filtered: [], code: 'tw', name: 'Taiwan (Province of China)' },
  tj: { show: false, channels: [], filtered: [], code: 'tj', name: 'Tajikistan' },
  tz: { show: false, channels: [], filtered: [], code: 'tz', name: 'Tanzania, United Republic of' },
  th: { show: false, channels: [], filtered: [], code: 'th', name: 'Thailand' },
  tt: { show: false, channels: [], filtered: [], code: 'tt', name: 'Trinidad and Tobago' },
  tn: { show: false, channels: [], filtered: [], code: 'tn', name: 'Tunisia' },
  tr: { show: false, channels: [], filtered: [], code: 'tr', name: 'Turkey' },
  ua: { show: false, channels: [], filtered: [], code: 'ua', name: 'Ukraine' },
  ae: { show: false, channels: [], filtered: [], code: 'ae', name: 'United Arab Emirates' },
  gb: {
    show: false,
    channels: [],
    filtered: [],
    code: 'gb',
    name: 'United Kingdom of Great Britain and Northern Ireland'
  },
  us: { show: false, channels: [], filtered: [], code: 'us', name: 'United States of America' },
  uy: { show: false, channels: [], filtered: [], code: 'uy', name: 'Uruguay' },
  uz: { show: false, channels: [], filtered: [], code: 'uz', name: 'Uzbekistan' },
  ve: {
    show: false,
    channels: [],
    filtered: [],
    code: 've',
    name: 'Venezuela (Bolivarian Republic of)'
  },
  vn: { show: false, channels: [], filtered: [], code: 'vn', name: 'Viet Nam' }
}
